### ISSUE TITLE
Cannot save fiddle ERRW: 1.0:6637

### ISSUE THREAD

**Issue by Kristina6403** [jsfiddle/jsfiddle-users#1929]
## Content of the fiddle:

```html
<body>
  <h1>Cannon River Inn</h1>
  <p>Located in Welch, MN</p>
  <div>
    <a href="http://google.com">Instagram</a>
  </div>
  <div class="OrangeLinks">
    <a href="http://google.com" class="OrangeLinks">Facebook</a>
  </div>
  <div id="ThirdLink" class="OrangeLinks">
    <a href="http://google.com">Maps</a>
  </div>
  <div class="OrangeLinks">
    Where your thirst is quenched
    <div id="nestedDiv">
      Nesting the tags
      <img
        src="https://tse3.mm.bing.net/th?id=OIP.ztLkMuZ-loJZ0mHqwDRBMgAAAA&pid=Api&P=0&h=220"
      />
    </div>
  </div>
</body>

```

```css
a {
  color: red;
}
a:hover {
  color: yellow;
}

.OrangeLinks {
  color: blue;
}
#ThirdLink a{
  color: teal;
  position: relative;
  animation-name: thirdlinkanimation;
  animation-duration: 1s;
  animation-iteration-count: 20;
  animation-direction:alternate;
  animation-timing-function: linear;
}

#ThirdLink a:hover {
  color: pink;
}
#nestedDiv {
   padding-left: 30px;
   border: 5px dotted pink;
   width: auto;
}
#nestedDiv:hover {
  animation-name: nestedDivanimation;
  animation-duration: 5s;
  animation-iteration-count: 1;
  animation-timing-function: ease;
}
img {
  display: block;
}
h1 {
  color: pink;
  font-family: Arial;
}
@keyframes nestedDivanimation {
  from {
    background-color: black;
  }
  to {
    background-color: blue;
  }
}
@keyframes thirdlinkanimation {
  from {
    left: 0px;
  }
  to {
    left: 200px;
  }
}
```

## Other details
Cannot save this fiddle. (ERRW:1.0:6637)

- Logged in: Yes
- Username: Kristina6504
