### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by tlahtilu** [jsfiddle/jsfiddle-users#1961]
### Error code

ERRW:0.7:SL0.1:EL0.1:TTH0.5

### Were you logged in?

Yes

### Your username (if logged in)

tlahtilu

### Your HTML

```html
<html>
<title>Tugas Kecil TI</title>
<head>
<h1>
Penerapan Teknologi Informasi di Perpustakaan
</h1>
<p><i>Information Technologies in Library</i>
</p>
</head>
<body>
Research kecil-kecilan udah kita lakuin untuk nemuin penerapan Teknologi Informasi di Perpustakaan, ini beberapa contoh yang menurut kita keren dan catchy!
<p><b>1. Virtual Library Tour</b></p>
<p> Virtual tour Perpustakaan UMS tuh semacam tur keliling perpustakaan, tapi versi online. Jadi enggak perlu datang langsung ke lokasi, cukup buka lewat website, nanti bisa lihat isi perpustakaan dari berbagai sudut secara 360 derajat. Fitur ini membantu banget buat yang ingin tahu fasilitas perpustakaan tanpa harus ribet ke kampus.</p>

<p>Di dalam virtual tour-nya, udah lengkap banget. Mulai dari ruang koleksi, ruang baca, referensi, sampai ruang diskusi, dan layanan lainnya juga bisa dilihat. Visualnya interaktif, jadi kesannya kayak lagi betulan jalan-jalan di dalam perpustakaan. Ini cocok banget buat mahasiswa baru atau siapa pun yang mau kenalan dulu sama perpustakaan UMS.</p>

<p>Aksesnya gampang, tinggal buka website resmi Perpustakaan UMS 
<a href="https://library.ums.ac.id/virtual-tour-perpus-ums/">Virtual Library Tour</a> terus pilih menu Virtual Tour. Dari situ tinggal klik dan jelajahi. Simpel, praktis, dan lumayan seru buat sekedar lihat-lihat atau siapin diri sebelum aktif pakai fasilitas perpustakaan.</p>
<p><b>2. Self Checkout Machine</b>
<p>Terdengar keren, bukan? Charleston County Public Library udah nerapin mesin ini dari tahun 2019. Proses peminjaman buku jadi mudah banget, pemustaka cukup scan kartu anggota, masukin PIN, terus taruh bukunya di pemindai RFID. Nanti mesin self checkout nya bakal bunyi kalua peminjamannya sukses. Pemustaka juga bisa pilih cetak struk langsung atau dikirim lewat email!Kalian bisa langsung check video YouTube ini ya!
<a href="https://youtu.be/rrUqZyQpr_k?si=CiEX33oqgNVkbjSJ">Self Checkout Machine</a></p>
<p><b>3. Automated Material Handling (AMH)</b>
<p>Sistem ini menggunakan conveyor belt untuk mengangkut, menyortir, dan mengelola buku yang dikembalikan oleh pengunjung. Sistem ini sering bekerja sama dengan RFID untuk pemindaian otomatis. Jadi, AMH itu mesin yang mengelola pengembalian buku secara otomatis. Setelah pemustaka ngembaliin buku ke drop box, sistem akan bawa buku ke area pemrosesan menggunakan conveyor belt. Bukunya dipindai dan disortir secara otomatis untuk dikembalikan ke rak yang sesuai atau untuk pemrosesan lebih lanjut. Rinciannya dapat dilihat di video ini ya! 
<a href="https://youtu.be/MVHOpvhAOWI?si=eNwpPHUV2IjvtfS_">Automated Material Handling</a></p>
<p>Dengan adanya kedua sistem tersebut, pustakawan akan lebih fokus dalam melakukan pekerjaannya, seperti memberi rekomendasi buku kepada pemustaka, efesiensi alur kerja, dan manajemen inventaris yang akurat. Jika penasaran dan ingin membaca lebih lanjut dengan detail sistemnya, temen-temen dapat mengunjungi website Lyngsoe Systems ya!</p>
</body>
</html>
```

### Your JavaScript

```javascript

```

### Your CSS

```css
body {
  background: linear-gradient(90deg, var(--color-1) 0%, var(--color-1) 25%, var(--color-2) 25%, var(--color-2) 50%, var(--color-3) 50%, var(--color-3) 75%, var(--color-4) 75%, var(--color-4) 100%);
}
body {
    background-color: #cac0b3;
background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='88' height='24' viewBox='0 0 88 24'%3E%3Cg fill-rule='evenodd'%3E%3Cg id='autumn' fill='%23c89233' fill-opacity='0.4'%3E%3Cpath d='M10 0l30 15 2 1V2.18A10 10 0 0 0 41.76 0H39.7a8 8 0 0 1 .3 2.18v10.58L14.47 0H10zm31.76 24a10 10 0 0 0-5.29-6.76L4 1 2 0v13.82a10 10 0 0 0 5.53 8.94L10 24h4.47l-6.05-3.02A8 8 0 0 1 4 13.82V3.24l31.58 15.78A8 8 0 0 1 39.7 24h2.06zM78 24l2.47-1.24A10 10 0 0 0 86 13.82V0l-2 1-32.47 16.24A10 10 0 0 0 46.24 24h2.06a8 8 0 0 1 4.12-4.98L84 3.24v10.58a8 8 0 0 1-4.42 7.16L73.53 24H78zm0-24L48 15l-2 1V2.18A10 10 0 0 1 46.24 0h2.06a8 8 0 0 0-.3 2.18v10.58L73.53 0H78z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
<p style="text-align: justify;"
}
```
