### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by huypham-max** [jsfiddle/jsfiddle-users#1967]
### Error code

9999

### Were you logged in?

Yes

### Your HTML

```html
<!DOCTYPE html>
<html lang="vi">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Cá Bò Phước Tỉnh</title>
  <link rel="stylesheet" href="style.css" />
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
</head>
<body>
  <header class="hero">
    <nav>
      <h1>Cá Bò Phước Tỉnh</h1>
      <ul>
        <li><a href="#about">Giới thiệu</a></li>
        <li><a href="#products">Sản phẩm</a></li>
        <li><a href="#contact">Liên hệ</a></li>
      </ul>
    </nav>
    <div class="hero-content">
      <h2>Cá Bò Tươi Ngon – Giao Tận Nơi</h2>
      <p>Ngư dân Phước Tỉnh – đánh bắt trong ngày, đảm bảo chất lượng</p>
      <a href="#contact" class="btn">Đặt hàng ngay</a>
    </div>
  </header>

  <section id="about" class="about section">
  <h2>Về chúng tôi</h2>
  <p>
    Chúng tôi là ngư dân lâu năm tại <strong>Phước Tỉnh – Bà Rịa</strong>, chuyên cung cấp <strong>cá bò khô thành phẩm</strong> chuẩn vị biển quê. 
    Cá được đánh bắt trực tiếp trong ngày, chọn lọc kỹ, làm sạch, tẩm gia vị nhẹ và phơi nắng tự nhiên 100% – không hoá chất, không chất bảo quản, Hàng loại A.
  </p>
  <p>
    Sản phẩm cá bò khô của chúng tôi thơm ngon, dai mềm, vị ngọt tự nhiên – phù hợp làm mồi nhậu, quà biếu hay ăn vặt gia đình. 
    Giao hàng toàn quốc – uy tín, tận tâm và luôn cam kết chất lượng trên từng con cá.
  </p>
</section>
  <section id="products" class="products section">
    <h2>Sản phẩm nổi bật</h2>
    <div class="product-grid">
      <div class="product">
        <img src="https://bizweb.dktcdn.net/thumb/large/100/455/816/products/khocabo4.jpg?v=1689125643393" alt="Cá bò tươi">
        <h3>Cá Bò Tươi</h3>
        <p>Giá: <strong>260.000đ/kg</strong></p>
      </div>
      <!-- Thêm sản phẩm nếu muốn -->
    </div>
  </section>

  <section id="contact" class="contact section">
    <h2>Liên hệ đặt hàng</h2>
    <p>📞 <strong>Gọi ngay:</strong> <a href="tel:0909123456">0798838994</a></p>
    <p>💬 <strong>Zalo:</strong> <a href="https://zalo.me/0798838994" target="_blank">Chat với chúng tôi</a></p>
    <p>📘 <strong>Facebook:</strong> <a href="https://www.facebook.com/profile.php?id=100026921019201" target="_blank">Cá Bò Phước Tỉnh</a></p>
  </section>

  <footer>
    <p>&copy; 2025 Cá Bò Phước Tỉnh. Thiết kế bởi nhà kinh doanh tương lai</p>
  </footer>

  <script src="script.js"></script>
</body>
</html>
```

### Your JavaScript

```javascript
function datHang() {
  alert("Cảm ơn bạn đã đặt hàng! Chúng tôi sẽ liên hệ sớm.");
}
```

### Your CSS

```css
/* Font tổng thể */
body {
  font-family: 'Roboto', sans-serif;
  margin: 0;
  padding: 0;
  line-height: 1.6;
  background-color:			#f0f0f0;
  color: #333;
}

/* Header + Navbar */
.hero {
  background: linear-gradient(to right,#e0f7f4, #319795);
  color: white;
  padding: 40px 20px;
  text-align: center;
}

.hero nav {
  display: flex;
  justify-content: space-between;
  align-items: center;
  max-width: 1100px;
  margin: auto;
  flex-wrap: wrap;
}

.hero nav h1 {
  font-size: 28px;
}

.hero nav ul {
  list-style: none;
  display: flex;
  gap: 20px;
}

.hero nav ul li a {
  color: white;
  text-decoration: none;
  font-weight: bold;
}

.hero-content h2 {
  font-size: 32px;
  margin-top: 30px;
}

.hero-content p {
  font-size: 18px;
  margin-bottom: 20px;
}

.btn {
  background-color: white;
  color: #2c7a7b;
  padding: 12px 24px;
  border-radius: 8px;
  font-weight: bold;
  text-decoration: none;
  transition: 0.3s ease;
}

.btn:hover {
  background-color: #e0f7f4;
  color: #007f5f;
}

/* Section chung */
.section {
  max-width: 1000px;
  margin: 60px auto;
  padding: 0 20px;
  text-align: center;
}

h2 {
  color: #007f5f;
  font-size: 28px;
  margin-bottom: 20px;
}

/* Sản phẩm */
.product-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 30px;
  margin-top: 30px;
}

.product {
  background-color: #fff;
  border-radius: 12px;
  box-shadow: 0 4px 12px rgba(0,0,0,0.05);
  padding: 20px;
  transition: transform 0.2s;
}

.product:hover {
  transform: translateY(-5px);
}

.product img {
  width: 100%;
  border-radius: 10px;
  margin-bottom: 10px;
}

/* Contact */
.contact p {
  font-size: 16px;
  margin-bottom: 10px;
}

.contact a {
  color: #007f5f;
  text-decoration: none;
  font-weight: bold;
}

/* Footer */
footer {
  background-color: #2c7a7b;
  color: white;
  text-align: center;
  padding: 20px 0;
  margin-top: 60px;
  font-size: 14px;
}
```
