### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by Vex3943** [jsfiddle/jsfiddle-users#1969]
### Error code

ERRW:0.81:TTH0.3:CD0.21:PU0.3

### Were you logged in?

Yes

### Your username (if logged in)

irisvex

### Your HTML

```html
<body>  <div class="table">
     
      <div class ="main_box"></div>
      <div class ="polaroid"></div>
        <div class ="polaroid_under"></div>
      
      <div class="text_box">
      <div class="text_box-id">
        <div class="text_box-inner-id">

<d>STILE UNO</d> <h>STILE DUE </h> <w> stile 3</w> <b>stile 4</b> <i>stile 5</i>
Nadifa Morowa Ouedraogo - Nata sotto il sole cocente del Kenya, protetta dal segno del Cancro e da una luna amica. Nel sangue le scorrono tradizioni millenarie dell'Africa ed il ribollente ardore del Brasile. Un animaletto selvaggio, estraneo dal mondo civilizzato, approda nelle lande umide dell'Inghilterra ad aprile 2026. <br><br> Piccola e minuta, eppure mentre i suoi piedi accarezzano la terra, la sua testa viaggia tra gli astri e le stelle ed i suoi occhi cercano nuovi mondi, antichi e mai nati. <br><br> A Uagadou il sogno che la identifica come Fwooper è nitido quanto un pizzico sul braccio, ad Hogwarts il suo smistamento è fumoso come polvere buio pesto. Può aver tranquillamente raggiunto il record per lo smistamento più lungo della storia, ben ventiquattro minuti che hanno come epilogo la casa di Priscilla Corvonero. Spruzzi di stelle su un viso piccolo e dolce, circondato da capelli che sembrano il retaggio di un leone. <br><br> Le ossa lucide che indossa come gioielli sono carcasse onorate dalla sua tribù ed il serpente che le vedete strisciare addosso è ciò che ha di più vicino al calore che ha lasciato in Kenya.<br><br>  Non sarà evento raro vederla mangiare con le mani, camminare scalza fuori dalle lezioni o dimenticarsi dell'esistenza della sua bacchetta, perdendola tra i ricci.
<br><br>

        </div>
       
        
      </div></div> 
<div class="credits"><br>
graphics by <bb>Iris</bb>
</div>

</div>
</body>
```

### Your JavaScript

```javascript

```

### Your CSS

```css
* ------------------------------ GENERICO ------------------------------ */

::-webkit-scrollbar {

     background: #000000;
     width: 0px;
}

::-moz-selection {

     color: #514936;
     background: #3c3125;
     text-shadow: 1px 1px 0px #1e1a15;
}

::selection {

     color: #514936;
     background: none;
     text-shadow: 0px 0px 0px #000!important;
}


/* ------------------------------ TABLE  ------------------------------ */

.table {background-color: #; position: relative;

    width: 550px; 
     height: 520px; 
     left: 50%;
     top: 50%;
     margin-left: -370px;
     margin-top: 60px;
}
     
/* ------------------------------ DETTAGLI  ------------------------------ */

    .main_box {position: absolute; z-index:2; float: left; overflow: none; opacity: 1; background-size: cover;

     width: 521px; 
     height: 379px;
     left: 50%;
     top: 50%;
     margin-left: -180px;
     margin-top: -280px;

     background-image: url(https://imgur.com/zYC1Bpm.png);
     background-position: 0px 0px;
     background-repeat: no-repeat;

}
.polaroid { position: absolute; z-index:4; float: left; overflow: none; opacity: 1; background-size: cover; -moz-transition: all ease-in-out 2s; -webkit-transition: all ease-in-out 2s; -o-transition: all ease-in-out 1s;  
 
 background-image: url(https://imgur.com/QYnkz9D.png);
	width: 274px; 
    	 height: 382px; 
     	  margin-left: 150px; 
     background-repeat: no-repeat;
     }
     
.polaroid:hover {  z-index:4; opacity:1;
    background-image: url(https://imgur.com/3wgQCcw.png);
    
     transition-delay: 1s;}


 /* ------------------------------ TESTO  ------------------------------ */
.text_box {  position: absolute; z-index:2; float: left; overflow: hidden; opacity: 0;
     -moz-transition: all ease-in-out 1s; -webkit-transition: all ease-in-out 1s; -o-transition: all ease-in-out 1s; 

   
     width:  271px; 
     height: 289px;
     margin-left: 160px;
     margin-top: 40px; /*-540*/
     
 background-repeat: no-repeat;
     background-image: url(https://imgur.com/ffiCN6N.png);
     transition-delay: 0.5s;
     
    

}
.table:hover .text_box {

     opacity:1;
    margin-left: 410px;
     margin-top: 40px; /*-540*/

     transition-delay: 1.5s;
}
.text_box-id { position: relative; z-index:3; float: left; overflow: hidden; opacity: 1;
     -moz-transition: all ease-out 1.5s; -webkit-transition: all ease-out 1.5s; -o-transition: all ease-out 1.5s; 

   
     width: 255px; 
     height: 280px; margin-top: 0px;
    
}

.text_box-inner-id { position: absolute; z-index:3; float: left; overflow: auto; opacity: 1;


  width: 220px;
     height: 240px;
     margin-left: 25px;
    margin-top: 20px;
     background: none;
       rotate:2deg;
      color: #a8a8a8;
     font-family: tahoma;
     font-size: 10px; 
     line-height: 9px; 
     letter-spacing: 0px;
     text-align: justify;
     
}



/* ------------------------------ TEXT STYLE ------------------------------ */


a {
     text-decoration:none!important;

}

d {
     color: #49441b;
     font-family: georgia;
     font-size: 9px;
     line-height: 9px;
     font-style: italic;
     font-weight: bold;
}

f {
     font-family: calibri; 
     color: #41381e;
     text-transform: uppercase;
     letter-spacing: 1px;
     font-weight: bold;
     font-size: 8px;
     line-height: 9px!important;
     letter-spacing: 2px; 
}

h {
     font-family: georgia; 
     text-transform: uppercase;
     font-size: 7px;
     line-height: 9px!important;
     letter-spacing: 3px; 
     color: #112209;
     text-shadow: 0px 1px 0px #111; 
} 

w {
     text-transform: uppercase;
     font-size: 8px;
     line-height: 9px!important;
     letter-spacing: 2px; 
     color: #7a6943; 
     background: #321b07; 

     padding-left:7px;
     padding-right:7px;
} 

z {
     letter-spacing:0px;
     color: #41381e;
}

/* ------------------------------ B - I - U - S ------------------------------ */

bb, i, s {
     color: #5c4c29;
}

s {
     letter-spacing:2px; 
     text-decoration: line-through wavy #41361e; 
     line-height: 9px;
}


/* ------------------------------ CREDITS ------------------------------ */

.credits { position: relative;  float: left; 

     width: 300px;
     left: 50%;
     margin-left: -150px; 
     height: 100px; 
     margin-top: 390px;
     background-color: none; 
  
     text-align: center; 
     font-family: tahoma; 
     text-transform: uppercase; 
     color: #777; 
     letter-spacing: 1px; 
     font-style: bold; 
     font-size: 8px; 
     text-shadow: 1px 1px 1px #000; 
}
```
