### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by Bruce-ST** [jsfiddle/jsfiddle-users#1971]
### Error code

ERRW:0.8:TTH0.5:L0.8

### Were you logged in?

Yes

### Your username (if logged in)

brucep

### Your HTML

```html
<div class="article">
  <div class="category">FASHION</div>
  <h1 class="title">
    Hoàng Thùy, Đỗ Hà chinh phục sàn runway 25 bậc thang dốc đứng trong show của NTK Hà Duy
  </h1>
  <p class="body">
    Đúng với tinh thần “thể thao thanh lịch”, Tory Burch đem đến những chiếc tank top phóng khoáng có thể dễ dàng phối với nhiều loại trang phục; đồ bơi thêu kim sa – không chỉ dành cho đi bơi mà còn có thể mặc như chiếc bodysuit duyên dáng khi phối cùng quần, chân váy… Bên cạnh đó còn có thắt lưng và cà vạt gợi nhắc đến võ phục.
  </p>
</div>
```

### Your JavaScript

```javascript

```

### Your CSS

```css
body {
  margin: 40px;
  background: #fff;
  font-family: Helvetica, sans-serif;
  color: #000;
}

.article {
  max-width: 900px;
  margin: 0 auto;
}

.category {
  font-size: 35px;
  line-height: 2.67em;
  text-transform: uppercase;
  letter-spacing: 0em;
  color: #FF0000; /* RD - red, adjust if you have a brand color */
  font-weight: 400;
}

.title {
  font-size: 64px;
  line-height: 4.83em;
  letter-spacing: 0em;
  color: #000; /* BL - black */
  font-weight: bold;
  margin: 20px 0;
}

.body {
  font-size: 24px;
  line-height: 2em;
  letter-spacing: 0em;
  color: #000;
  font-weight: 400;
  text-align: left;
}
```
