### ISSUE TITLE
gaixinhcuchot

### ISSUE THREAD

**Issue by meow851** [jsfiddle/jsfiddle-users#1983]
### Error code

0,6K0

### Were you logged in?

Yes

### Your username (if logged in)

meow518

### Your HTML

```html
<!DOCTYPE html><html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Sinh nhật Nguyệt Minh</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      background-image: url('https://i.imgur.com/OvMZBs9.jpg'); /* ảnh nền đồi hoa và bánh sinh nhật */
      background-size: cover;
      background-position: center;
      font-family: Arial, sans-serif;
      overflow: hidden;
    }
    h1 {
      text-align: center;
      margin-top: 30px;
      font-size: 3em;
      color: #fff;
      text-shadow: 0 0 10px #ff00cc, 0 0 20px #ff00cc;
      animation: glow 2s infinite alternate;
    }
    @keyframes glow {
      from { text-shadow: 0 0 10px #ff00cc; }
      to { text-shadow: 0 0 20px #ff00cc, 0 0 30px #ff33cc; }
    }
    .main-img {
      display: block;
      margin: 30px auto;
      max-width: 60%;
      border-radius: 20px;
      box-shadow: 0 0 20px rgba(255, 255, 255, 0.6);
    }
    canvas {
      position: fixed;
      top: 0;
      left: 0;
      width: 100vw;
      height: 100vh;
      pointer-events: none;
    }
  </style>
</head>
<body>
  <h1>Mừng Em Gái Nguyệt Minh Cực Hot 18+</h1>
  <img class="main-img" src="nguyetminh.jpg" alt="Nguyet Minh" /><canvas id="fireworks"></canvas>

  <audio autoplay loop>
    <source src="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3" type="audio/mpeg" />
  </audio>  <script>
    // Simple fireworks effect
    const canvas = document.getElementById('fireworks');
    const ctx = canvas.getContext('2d');
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;

    const fireworks = [];

    function random(min, max) {
      return Math.random() * (max - min) + min;
    }

    class Firework {
      constructor() {
        this.x = random(0, canvas.width);
        this.y = random(0, canvas.height / 2);
        this.radius = random(2, 5);
        this.color = `hsl(${Math.floor(random(0, 360))}, 100%, 50%)`;
        this.alpha = 1;
        this.fade = random(0.01, 0.03);
      }
      draw() {
        ctx.globalAlpha = this.alpha;
        ctx.beginPath();
        ctx.arc(this.x, this.y, this.radius, 0, Math.PI * 2);
        ctx.fillStyle = this.color;
        ctx.fill();
        ctx.globalAlpha = 1;
      }
      update() {
        this.alpha -= this.fade;
      }
    }

    function animate() {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      if (Math.random() < 0.1) {
        for (let i = 0; i < 20; i++) {
          fireworks.push(new Firework());
        }
      }
      fireworks.forEach((f, i) => {
        f.update();
        f.draw();
        if (f.alpha <= 0) fireworks.splice(i, 1);
      });
      requestAnimationFrame(animate);
    }
    animate();
  </script></body>
</html>
```

### Your JavaScript

```javascript
<!DOCTYPE html><html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Sinh nhật Nguyệt Minh</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      background-image: url('https://i.imgur.com/OvMZBs9.jpg'); /* ảnh nền đồi hoa và bánh sinh nhật */
      background-size: cover;
      background-position: center;
      font-family: Arial, sans-serif;
      overflow: hidden;
    }
    h1 {
      text-align: center;
      margin-top: 30px;
      font-size: 3em;
      color: #fff;
      text-shadow: 0 0 10px #ff00cc, 0 0 20px #ff00cc;
      animation: glow 2s infinite alternate;
    }
    @keyframes glow {
      from { text-shadow: 0 0 10px #ff00cc; }
      to { text-shadow: 0 0 20px #ff00cc, 0 0 30px #ff33cc; }
    }
    .main-img {
      display: block;
      margin: 30px auto;
      max-width: 60%;
      border-radius: 20px;
      box-shadow: 0 0 20px rgba(255, 255, 255, 0.6);
    }
    canvas {
      position: fixed;
      top: 0;
      left: 0;
      width: 100vw;
      height: 100vh;
      pointer-events: none;
    }
  </style>
</head>
<body>
  <h1>Mừng Em Gái Nguyệt Minh Cực Hot 18+</h1>
  <img class="main-img" src="nguyetminh.jpg" alt="Nguyet Minh" /><canvas id="fireworks"></canvas>

  <audio autoplay loop>
    <source src="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3" type="audio/mpeg" />
  </audio>  <script>
    // Simple fireworks effect
    const canvas = document.getElementById('fireworks');
    const ctx = canvas.getContext('2d');
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;

    const fireworks = [];

    function random(min, max) {
      return Math.random() * (max - min) + min;
    }

    class Firework {
      constructor() {
        this.x = random(0, canvas.width);
        this.y = random(0, canvas.height / 2);
        this.radius = random(2, 5);
        this.color = `hsl(${Math.floor(random(0, 360))}, 100%, 50%)`;
        this.alpha = 1;
        this.fade = random(0.01, 0.03);
      }
      draw() {
        ctx.globalAlpha = this.alpha;
        ctx.beginPath();
        ctx.arc(this.x, this.y, this.radius, 0, Math.PI * 2);
        ctx.fillStyle = this.color;
        ctx.fill();
        ctx.globalAlpha = 1;
      }
      update() {
        this.alpha -= this.fade;
      }
    }

    function animate() {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      if (Math.random() < 0.1) {
        for (let i = 0; i < 20; i++) {
          fireworks.push(new Firework());
        }
      }
      fireworks.forEach((f, i) => {
        f.update();
        f.draw();
        if (f.alpha <= 0) fireworks.splice(i, 1);
      });
      requestAnimationFrame(animate);
    }
    animate();
  </script></body>
</html>
```

### Your CSS

```css
<!DOCTYPE html><html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Sinh nhật Nguyệt Minh</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      background-image: url('https://i.imgur.com/OvMZBs9.jpg'); /* ảnh nền đồi hoa và bánh sinh nhật */
      background-size: cover;
      background-position: center;
      font-family: Arial, sans-serif;
      overflow: hidden;
    }
    h1 {
      text-align: center;
      margin-top: 30px;
      font-size: 3em;
      color: #fff;
      text-shadow: 0 0 10px #ff00cc, 0 0 20px #ff00cc;
      animation: glow 2s infinite alternate;
    }
    @keyframes glow {
      from { text-shadow: 0 0 10px #ff00cc; }
      to { text-shadow: 0 0 20px #ff00cc, 0 0 30px #ff33cc; }
    }
    .main-img {
      display: block;
      margin: 30px auto;
      max-width: 60%;
      border-radius: 20px;
      box-shadow: 0 0 20px rgba(255, 255, 255, 0.6);
    }
    canvas {
      position: fixed;
      top: 0;
      left: 0;
      width: 100vw;
      height: 100vh;
      pointer-events: none;
    }
  </style>
</head>
<body>
  <h1>Mừng Em Gái Nguyệt Minh Cực Hot 18+</h1>
  <img class="main-img" src="nguyetminh.jpg" alt="Nguyet Minh" /><canvas id="fireworks"></canvas>

  <audio autoplay loop>
    <source src="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3" type="audio/mpeg" />
  </audio>  <script>
    // Simple fireworks effect
    const canvas = document.getElementById('fireworks');
    const ctx = canvas.getContext('2d');
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;

    const fireworks = [];

    function random(min, max) {
      return Math.random() * (max - min) + min;
    }

    class Firework {
      constructor() {
        this.x = random(0, canvas.width);
        this.y = random(0, canvas.height / 2);
        this.radius = random(2, 5);
        this.color = `hsl(${Math.floor(random(0, 360))}, 100%, 50%)`;
        this.alpha = 1;
        this.fade = random(0.01, 0.03);
      }
      draw() {
        ctx.globalAlpha = this.alpha;
        ctx.beginPath();
        ctx.arc(this.x, this.y, this.radius, 0, Math.PI * 2);
        ctx.fillStyle = this.color;
        ctx.fill();
        ctx.globalAlpha = 1;
      }
      update() {
        this.alpha -= this.fade;
      }
    }

    function animate() {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      if (Math.random() < 0.1) {
        for (let i = 0; i < 20; i++) {
          fireworks.push(new Firework());
        }
      }
      fireworks.forEach((f, i) => {
        f.update();
        f.draw();
        if (f.alpha <= 0) fireworks.splice(i, 1);
      });
      requestAnimationFrame(animate);
    }
    animate();
  </script></body>
</html>
```
