### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by kingramzan54** [jsfiddle/jsfiddle-users#1999]
### Error code

1 . 0 : k1 . 0

### Were you logged in?

Yes

### Your username (if logged in)

kingramzan832@gmail.com

### Your HTML

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>AK Game - Save System</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>

  <div class="game-container">
    <h1>AK Game</h1>

    <div id="playerStats">
      <p id="playerHealth">Health: 100</p>
      <p id="playerLevel">Level: 1</p>
      <p id="playerXP">XP: 0</p>
    </div>

    <div id="saveLoadSection">
      <h2>Save & Load Game</h2>
      <button id="saveGameBtn">Save Game</button>
      <button id="loadGameBtn">Load Game</button>
    </div>
  </div>

  <script src="script.js"></script>
</body>
</html>
```

### Your JavaScript

```javascript
let playerData = {
  health: 100,
  level: 1,
  experience: 0,
};

// Save game data
document.getElementById("saveGameBtn").addEventListener("click", function () {
  localStorage.setItem("playerData", JSON.stringify(playerData));
  alert("Game Saved!");
});

// Load game data
document.getElementById("loadGameBtn").addEventListener("click", function () {
  const savedData = JSON.parse(localStorage.getItem("playerData"));
  if (savedData) {
    playerData = savedData;
    updateGameData();
    alert("Game Loaded!");
  } else {
    alert("No saved data found!");
  }
});

// Update game display
function updateGameData() {
  document.getElementById("playerHealth").textContent = `Health: ${playerData.health}`;
  document.getElementById("playerLevel").textContent = `Level: ${playerData.level}`;
  document
```

### Your CSS

```css
body {
  font-family: Arial, sans-serif;
  background: #121212;
  color: white;
  margin: 0;
  padding: 0;
}

.game-container {
  padding: 30px;
  max-width: 600px;
  margin: auto;
  background: #1e1e1e;
  border-radius: 10px;
  box-shadow: 0 0 10px #000;
}

button {
  padding: 10px 15px;
  margin: 10px 5px;
  background: #333;
  border: none;
  color: white;
  cursor: pointer;
  border-radius: 5px;
}

button:hover {
  background: #555;
}
```
