### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by cicekasigikadin** [jsfiddle/jsfiddle-users#2003]
### Error code

No error code shown. Save button does not work, nothing happens.

### Were you logged in?

Yes

### Your username (if logged in)

Çiçekaşığıkadın 

### Your HTML

```html
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Moon+ Reader Stili - Giriş Yap</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <!-- Giriş Bölməsi -->
        <div class="login-box">
            <h2>Moon+ Reader Girişi</h2>
            <form action="login.php" method="post">
                <div class="input-group">
                    <input type="text" name="username" required>
                    <label>Kullanıcı Adı</label>
                </div>
                <div class="input-group">
                    <input type="password" name="password" required>
                    <label>Şifre</label>
                </div>
                <button type="submit">Giriş Yap</button>
            </form>
        </div>

        <!-- E-kitap Yükleme Bölməsi -->
        <div class="upload-box">
            <h2>E-Kitap Yükle</h2>
            <form action="upload.php" method="POST" enctype="multipart/form-data">
                <div class="input-group">
                    <input type="file" name="ebook" id="ebook" accept=".pdf, .epub, .mobi" required>
                    <label>Dosya Seç</label>
                </div>
                <button type="submit">Yükle</button>
            </form>
        </div>
    </div>
</body>
</html>
```

### Your JavaScript

```javascript
// Giriş formunun yoxlanması
document.querySelector('.login-box form').addEventListener('submit', function(event) {
    const username = document.querySelector('input[name="username"]').value;
    const password = document.querySelector('input[name="password"]').value;

    // Sadə yoxlama - əslində serverdə yoxlama aparılmalıdır
    if (username === '' || password === '') {
        alert('Kullanıcı adı ve şifre boş bırakılamaz!');
        event.preventDefault(); // Formun göndərilməsini dayandırır
    }
});

// E-kitap yükləmə formunun yoxlanması
document.querySelector('.upload-box form').addEventListener('submit', function(event) {
    const ebookFile = document.querySelector('input[type="file"]').files[0];

    // Fayl yoxlama (pdf, epub, mobi formatları)
    if (!ebookFile) {
        alert('Lütfen bir dosya seçin!');
        event.preventDefault();
        return;
    }

    const allowedExtensions = ['pdf', 'epub', 'mobi'];
    const fileExtension = ebookFile.name.split('.').pop().toLowerCase();
    
    if (!allowedExtensions.includes(fileExtension)) {
        alert('İzin verilen dosya formatları: PDF, EPUB, MOBI.');
        event.preventDefault(); // Fayl yüklənməsini dayandırır
    }
});
```

### Your CSS

```css
@import url('https://fonts.googleapis.com/css?family=Roboto:400,500&display=swap');

body {
  background-color: #121212;
  color: #e0e0e0;
  font-family: 'Roboto', sans-serif;
  margin: 0;
  padding: 0;
}

/* Ortak konteyner ayarları */
.container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
}

/* Login ve Yükleme Kutuları */
.login-box,
.upload-box {
  background: #1e1e1e;
  padding: 40px;
  border-radius: 10px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.5);
  width: 320px;
  text-align: center;
}

.login-box h2,
.upload-box h2 {
  margin-bottom: 20px;
  font-weight: 500;
}

/* Input Grupları (Animasyonlu label için) */
.input-group {
  position: relative;
  margin-bottom: 30px;
}
.input-group input[type="text"],
.input-group input[type="password"],
.input-group input[type="file"] {
  width: 100%;
  padding: 10px 10px 10px 5px;
  background: none;
  border: none;
  border-bottom: 1px solid #e0e0e0;
  color: #e0e0e0;
  outline: none;
}
.input-group label {
  position: absolute;
  top: 10px;
  left: 5px;
  transition: 0.3s;
  pointer-events: none;
}
.input-group input:focus ~ label,
.input-group input:valid ~ label {
  top: -10px;
  font-size: 12px;
  color: #03a9f4;
}

/* Buton Stili */
button {
  width: 100%;
  padding: 10px;
  background: #03a9f4;
  border: none;
  border-radius: 5px;
  color: #fff;
  font-weight: 500;
  cursor: pointer;
  transition: background 0.3s;
}
button:hover {
  background: #0288d1;
}

/* Hata Mesajı */
.error {
  color: #ff5252;
  text-align: center;
}

/* Bağlantı Stili */
.links {
  margin-top: 20px;
}
.link {
  color: #03a9f4;
  text-decoration: none;
  margin: 0 10px;
}
.link:hover {
  color: #0288d1;
}
```
