### ISSUE TITLE
Cannot save fiddle

### ISSUE THREAD

**Issue by ekros** [jsfiddle/jsfiddle-users#2007]
### Error code

ERRW:0.7:CE0.7

### Were you logged in?

Yes

### Your username (if logged in)

ekros

### Your HTML

```html
<!-- 1. centra este elemento usando flex -->
<div class="container c1">
    <div class="flex-item">item 1</div>
</div>

<!-- 2. coloca los elementos en orden inverso (derecha-izquierda) -->
<div class="container c2">
    <div class="flex-item red">item 1</div>
    <div class="flex-item green">item 2</div>
    <div class="flex-item yellow">item 3</div>
</div>

<!-- 3. añade un espaciado de 5px entre elementos -->
<div class="container c3">
    <div class="flex-item red">item 1</div>
    <div class="flex-item green">item 2</div>
    <div class="flex-item yellow">item 3</div>
</div>

<!-- 4. item 4 no se visualiza correctamente. Porque?? -->
<div class="container">
    <div class="flex-item red">item 1</div>
    <div class="flex-item green">item 2</div>
    <div class="flex-item yellow">item 3
      <div class="flex-item yellow">item 4</div>
    </div>
</div>

<!-- 5. Intercambia item 2 e item 4 -->
<div class="container c5">
    <div class="flex-item red">item 1</div>
    <div class="flex-item green">item 2</div>
    <div class="flex-item yellow">item 3</div>
    <div class="flex-item orange">item 4</div>
</div>

<!-- 6. alinea las cajas a la derecha -->
<div class="container c6">
    <div class="flex-item red">item 1</div>
    <div class="flex-item green">item 2</div>
    <div class="flex-item yellow">item 3</div>
    <div class="flex-item orange">item 4</div>
</div>

<!-- 7. distribuye las cajas verticalmente y de abajo a arriba -->
<div class="container c7">
    <div class="flex-item red">item 1</div>
    <div class="flex-item green">item 2</div>
    <div class="flex-item yellow">item 3</div>
    <div class="flex-item orange">item 4</div>
</div>

<!-- 8. cajas equispaciadas, prueba diversas variantes -->
<div class="container c8">
    <div class="flex-item red">item 1</div>
    <div class="flex-item green">item 2</div>
    <div class="flex-item yellow">item 3</div>
    <div class="flex-item orange">item 4</div>
</div>

<!-- 9. layout horizontal - cajas alineadas verticalmente en el centro excepto la última -->
<div class="container c9">
    <div class="flex-item red">item 1</div>
    <div class="flex-item green">item 2</div>
    <div class="flex-item yellow">item 3</div>
    <div class="flex-item orange">item 4</div>
</div>
```

### Your JavaScript

```javascript

```

### Your CSS

```css
.container {
    display: flex;
    border: 1px solid black;
    height: 300px;
    width: 100%;
}
.flex-item {
  width: 100px;
  height: 100px;
  background: palegreen;
}
.red {
  background: red;
}
.green {
  background: green;
}
.yellow {
  background: yellow;
}
.orange {
  background: orange;
}
.pink {
  background: pink;
}

.c1 {
  /* centrar */
}
.c2 {
  /* orden inverso */
}
.c3 {
  /* 5px de espaciado entre elementos */
}
.c5 {
  /* Intercambia item 2 e item 4*/
}
.c6 {
  /* alinea cajas a la derecha */
}
.c7 {
  /* vertical y de abajo a arriba */
}
.c8 {
  /* cajas equispaciadas */
}
.c9 {
  /* layout horizontal. Alineadas verticalmente en el centro excepto la última */
}
```
