### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by Mr-sai-9885** [jsfiddle/jsfiddle-users#2013]
### Error code

ERRW:1.0:K1.0:SL0.1:PU0.3

### Were you logged in?

Yes

### Your username (if logged in)

Smart_Coder

### Your HTML

```html
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>

<body>
    <div id="section-home">
        <div class="tour d-flex flex-column justify-content-end ">
            <div class="t-card ">
                <h1 class="main-heading">
                    Tourism
                </h1>
                <p class="paragraph-home">
                    Plan your trip.
                </p>
                <button class="mainbutton" onclick="display('section-fav')"> Get Started </button>
            </div>
        </div>
    </div>
    <div id="section-fav">
        <div class="main ">
            <h1>Favorite Places</h1>
            <div onclick="display('section-Tajmahal')">
                <div class="holecard d-flex flex-row">
                    <div class="textcard">
                        <h1 class="heading">Taj mahal</h1>
                        <p class="para">Taj Mahal, Views of Taj Mahal, Day Tours, Night Viewing, Travel Information, Photo Gallery, Contact Us, Helpdesk, Taj Mahal Timing Book your Perfect Place to Stay near the Taj Mahal. No Reservation Costs. Great Rates. Choose from a wide range of properties which Booking.com offers. Search now! Read Real Guest Reviews. Save 10% with Genius. Great Availability. Flight...</p>

                    </div>
                    <div class="imacard d-flex flex-column justify-content-center">
                        <img src="https://cdn.pixabay.com/photo/2020/06/05/21/09/cultural-tourism-5264542_1280.jpg" class="image" />
                    </div>
                </div>
            </div>
            <div onclick="display('section-andaman')">
                <div class="holecard d-flex flex-row">
                    <div class="textcard">
                        <h1 class="heading">Andaman and Nicobar Islands</h1>
                        <p class="para">Replete with turquoise blue water beaches and a bit of history, Andaman & Nicobar Islands is a little slice of paradise tucked around 1,400 km away from the east coast of mainland India. Port Blair, the capital of this union territory, has a major airport and seaport connected with the rest of t...</p>

                    </div>
                    <div class="imacard d-flex flex-column justify-content-center">
                        <img src="https://www.holidify.com/images/bgImages/ANDAMAN-NICOBAR-ISLANDS.jpg" class="image" />
                    </div>
                </div>
            </div>
            <div onclick="display('section-ooty')">
                <div class="holecard d-flex flex-row">
                    <div class="textcard">
                        <h1 class="heading">Ooty</h1>
                        <p class="para">Nestled amidst Nilgiri hills, Ooty, also known as Udagamandalam, is a hill station in Tamil Nadu which serves as a top-rated tourist destination. Once regarded as the summer headquarters of the East India Company, the Queen of the hills is a picturesque getaway.</p>
                    </div>
                    <div class="imacard d-flex flex-column justify-content-center">
                        <img src="https://www.holidify.com/images/bgImages/OOTY.jpg" class="image" />
                    </div>
                </div>
            </div>
            <div onclick="display('section-city')">
                <div class="holecard d-flex flex-row">
                    <div class="textcard">
                        <h1 class="heading">Jaisalmer (Golden City</h1>
                        <p class="para">Jaisalmer, a mesmerizing destination nestled in the heart of the Thar Desert, is a jewel in the crown of Rajasthan. Often referred to as the "Golden City," Jaisalmer captivates visitors with its sandstone architecture, picturesque landscapes, and rich cultural heritage. The city is adorned with...</p>
                    </div>
                    <div class="imacard d-flex flex-column justify-content-center">
                        <img src="https://www.holidify.com/images/bgImages/JAISALMER.jpg" class="image" />
                    </div>
                </div>
                <button class="btn btn-dark" onclick="display('section-home')">back</button>
            </div>
        </div>
    </div>
    <div id="section-Tajmahal">
        <div class="detailed-view-card">
            <h1 class="detailed-view-heading">Detailed View</h1>
            <div class="card">
                <div class="card-carousal">
                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="https://d1tgh8fmlzexmh.cloudfront.net/ccbp-static-website/tajmahal-c1-img.png" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="https://d1tgh8fmlzexmh.cloudfront.net/ccbp-static-website/tajmahal-c2-img.png" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="https://d1tgh8fmlzexmh.cloudfront.net/ccbp-static-website/tajmahal-c3-img.png" class="d-block w-100" alt="...">
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
                <div class="text">
                    <h1 class="text-heading"> Taj Mahal</h1>
                    <p class="para">
                        The Taj Mahal is considered to be the greatest architectural
                        achievement in the whole range of Indo-Islamic architecture. Its
                        recognised architectonic beauty has a rhythmic combination of solids
                        and voids, concave and convex and light shadow; such as arches and
                        domes further increases the aesthetic aspect. Not a piece of
                        architecture, as other buildings are, but the proud passions of an
                        emperor’s love wrought in living stones.</p>
                </div>

            </div>

            <div class="d-flex d-row justify-content-end">
                <div class="d-flex d-row justify-content-start" onclick="display('section-fav')">
                    <button class="btn btn-dark">back</button>
                </div>
                <div class="d-flex flex-row justify-content-end" onclick="display('section-home')">
                    <button class="btn btn-primary ">Home</button>
                </div>
            </div>
        </div>

    </div>
    <div id="section-andaman">
        <div class="detailed-view-card">
            <h1 class="detailed-view-heading">Detailed View</h1>
            <div class="card">
                <div class="card-carousal">
                    <div id="andaman" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#andaman" data-slide-to="0" class="active"></li>
                            <li data-target="#ndaman" data-slide-to="1"></li>
                            <li data-target="#andaman" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="https://tse1.mm.bing.net/th?id=OIP.jjK7Ah_eSEhDQ5tgK3zI9wHaEo&rs=1&pid=ImgDetMain" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="https://travelogyindia.b-cdn.net/storage/app/upload/jolly-buoy-island-andaman.jpg" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="https://upload.wikimedia.org/wikipedia/commons/6/63/Havelock%2C_Andaman_%26_Nicobar_Islands.JPG" class="d-block w-100" alt="...">
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#andaman" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#andaman" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
                <div class="text">
                    <h1 class="text-heading"> Andaman and Nicobar Island</h1>
                    <p class="para">
                        The Andaman and Nicobar Islands is a union territory of India comprising 572 islands,
                        of which only 38 are inhabited
                    </P>
                    <ul class="para">
                        <li>Country : India</li>
                        <li>Elevation568 m (1,864 ft)</li>
                        <li>RegionEast India</li>
                        <li>1 November 1956</li>
                    </ul>
                </div>
                <div class="d-flex d-row justify-content-end">
                    <div class="d-flex d-row justify-content-start" onclick="display('section-fav')">
                        <button class="btn btn-dark">back</button>
                    </div>
                    <div class="d-flex flex-row justify-content-end" onclick="display('section-home')">
                        <button class="btn btn-primary ">Home</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="section-ooty">
        <div class="detailed-view-card">
            <h1 class="detailed-view-heading">Detailed View</h1>
            <div class="card">
                <div class="card-carousal">
                    <div id="ooty" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#ooty" data-slide-to="0" class="active"></li>
                            <li data-target="#ooty" data-slide-to="1"></li>
                            <li data-target="#ooty" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="https://1.bp.blogspot.com/-MFdcIPJKGnU/YDsJVZLwSJI/AAAAAAAAABE/Y80Qe081ObsobvvTO-8dMy56TluA0ZREACLcBGAsYHQ/w1200-h630-p-k-no-nu/ooty_must_visit_hillstation.jpg" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="https://www.clubmahindra.com/blog/media/section_images/85-05551bc91ca7f62.jpg" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="https://images.hindustantimes.com/img/2023/01/11/1600x900/mugi-jo-6qUltw7SjzM-unsplash_1669276738103_1673425680248_1673425680248.jpg" class="d-block w-100" alt="...">
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#ooty" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#ooty" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
                <div class="text">
                    <h1 class="text-heading"> Ooty</h1>
                    <p class="para">
                        A hill station in Tamil Nadu, India, known for its tea plantations,
                        Nilgiri Mountain Railway, and natural beauty.
                        Ooty's landscapes, wildlife, heritage, and culture.
                    </P>
                    <ul class="para">
                        <li>Nilgiris mountain range.</li>
                        <li>Misty dawn in Ooty.</li>
                        <li>Ooty train.</li>
                        <li>Udhagamandalam (Ooty) from above.</li>
                    </ul>
                </div>
                <div class="d-flex d-row justify-content-end">
                    <div class="d-flex d-row justify-content-start" onclick="display('section-fav')">
                        <button class="btn btn-dark">back</button>
                    </div>
                    <div class="d-flex flex-row justify-content-end" onclick="display('section-home')">
                        <button class="btn btn-primary ">Home</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div id="section-city">
        <div class="detailed-view-card">
            <h1 class="detailed-view-heading">Detailed View</h1>
            <div class="card">
                <div class="card-carousal">
                    <div id="city" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#city" data-slide-to="0" class="active"></li>
                            <li data-target="#city" data-slide-to="1"></li>
                            <li data-target="#city" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/new-york-golden-city-regina-geoghan.jpg" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="https://th.bing.com/th/id/OIP.EM57uEiLVMX-xoz7WnrIHwHaDq?rs=1&pid=ImgDetMain" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="https://cdnb.artstation.com/p/assets/images/images/001/390/003/large/andrew-suryadi-the-golden-city.jpg?1445580833" class="d-block w-100" alt="...">
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#city" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#city" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
                <div class="text">
                    <h1 class="text-heading">Jaisalmer (Goldan City)</h1>
                    <p class="para">
                        Jaisalmer (pronunciation) , nicknamed The Golden city,
                        is a city in the north-western Indian state of Rajasthan,
                        located 575 kilometres (357 mi) west of the state capital Jaipur,
                        in the heart of the Thar Desert. It serves as
                    </P>
                    <ul class="para">
                        <li>Joseph Pacheco.</li>
                        <li>Sonargaon Dhaka Picture. </li>
                        <li>golden-yellow hue that it imparts to the entire city</li>
                        <li>Spread across 118 Acres.</li>
                    </ul>
                </div>
                <div class="d-flex d-row justify-content-end">
                    <div class="d-flex d-row justify-content-start" onclick="display('section-fav')">
                        <button class="btn btn-dark">back</button>
                    </div>
                    <div class="d-flex flex-row justify-content-end" onclick="display('section-home')">
                        <button class="btn btn-primary ">Home</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <script type="text/javascript" src="https://d1tgh8fmlzexmh.cloudfront.net/ccbp-static-website/js/ccbp-ui-kit.js"></script>

</body>

</html>
```

### Your JavaScript

```javascript

```

### Your CSS

```css
@import url('https://fonts.googleapis.com/css2?family=Bree+Serif&family=Caveat:wght@400;700&family=Lobster&family=Monoton&family=Open+Sans:ital,wght@0,400;0,700;1,400;1,700&family=Playfair+Display+SC:ital,wght@0,400;0,700;1,700&family=Playfair+Display:ital,wght@0,400;0,700;1,700&family=Roboto:ital,wght@0,400;0,700;1,400;1,700&family=Source+Sans+Pro:ital,wght@0,400;0,700;1,700&family=Work+Sans:ital,wght@0,400;0,700;1,700&display=swap');

.tour {
    background-color: lightblue;
    text-align: center;
    background-image: url("https://islandwatersportshawaii.com/wp-content/uploads/2024/01/hawaii-beach.jpg");
    background-size: cover;
    height: 100vh;
}

.main-heading {
    color: blue;
    text-decoration: underline;

}

.t-card {
    background-color: white;
    border-top-left-radius: 50px;
    border-top-right-radius: 50px;
    padding: 5px;

}

.paragraph-home {
    color: black;
}

.mainbutton {
    color: white;
    background-color: #3ce647;
    height: 36px;
    width: 138px;
    border-radius: 25px;

}





.main {
    background-image: url("https://www.onecuriousguide.com/wp-content/uploads/2024/08/bd2cc078-ef98-4b3e-ba42-703fa765f3a4-768x768.jpg");
    background-size: cover;
    height: 170vh;
    width: 100vw;
    padding: 5px;
    font-family: Roboto;

}

.holecard {
    background-color: white;
    font-size: 12px;
    padding: 15px;
    border-radius: 20px;
    margin: 30px;
}

.textcard {
    font-family: Roboto;


}

.image {
    height: 70px;
    width: 70px;
}

.heading {
    font-size: 25px;
    font-family: Roboto;
    font-weight: bold;

}





.detailed-view-card {
    background-image: url("https://d1tgh8fmlzexmh.cloudfront.net/ccbp-static-website/seabg.png");
    background-size: cover;
    height: 100vh;
    border-radius: 15px;
}

.detailed-view-heading {
    color: white;
    font-family: Roboto;
    font-size: 30px;
    font-weight: bold;
    padding: 16px;
}

.text {
    padding: 20px;
    font-family: Roboto;
    font-weight: normal;
}

.text-heading {
    font-family: Roboto;
    font-size: 30px;
    font-weight: bold;

}

.card {
    margin: 30px;
}
```
