### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by WILLAM56585** [jsfiddle/jsfiddle-users#2015]
### Error code

nnn

### Were you logged in?

Yes

### Your HTML

```html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Jogo de Memória - Futebol</title>
  <link rel="stylesheet" href="styles.css">
  <script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.9.2/dist/confetti.browser.min.js"></script>
</head>
<body class="background-default">
  <div class="loading-screen">
    <h1>Carregando...</h1>
    <div class="progress-bar-container">
      <div class="progress-bar"></div>
    </div>
    <p class="loading-percent">0%</p>
    <p class="loading-error hidden"></p>
    <button id="skip-audio-btn" class="hidden">Pular Áudios (Teste)</button>
  </div>

  <div class="country-screen hidden">
    <h1>Jogo de Memória - Futebol</h1>
    <div class="country-buttons">
      <button class="country-btn" data-country="england">England</button>
      <button class="country-btn" data-country="spain">Spain</button>
      <button class="country-btn" data-country="brazil" disabled>Brazil ??</button>
    </div>
    <div class="menu-buttons">
      <button id="settings-btn">Configurações</button>
      <button id="skins-btn">Skins</button>
      <button id="ranking-btn">Ranking</button>
    </div>
  </div>

  <div class="settings-screen hidden">
    <h1>Configurações</h1>
    <label><input type="checkbox" id="background-music-toggle" checked> Música de fundo</label>
    <label><input type="checkbox" id="sound-effects-toggle" checked> Efeitos sonoros</label>
    <button id="back-to-country-btn">Voltar</button>
  </div>

  <div class="skins-screen hidden">
    <h1>Escolher Skin</h1>
    <div class="skin-buttons">
      <button class="skin-btn" data-skin="default">Padrão</button>
      <button class="skin-btn" data-skin="dark"><span class="locked-overlay">??</span>Escuro</button>
      <button class="skin-btn" data-skin="stadium"><span class="locked-overlay">??</span>Estádio</button>
    </div>
    <button id="back-to-country-from-skins-btn">Voltar</button>
  </div>

  <div class="ranking-screen hidden">
    <h1>Ranking</h1>
    <ol id="ranking-list"></ol>
    <button id="back-to-country-from-ranking-btn">Voltar</button>
  </div>

  <div class="difficulty-screen hidden">
    <h1>Escolha a Dificuldade</h1>
    <button class="difficulty-btn" data-difficulty="easy">Fácil</button>
    <button class="difficulty-btn" data-difficulty="medium">Médio</button>
    <button class="difficulty-btn" data-difficulty="hard">Difícil</button>
    <button id="back-to-country-from-difficulty-btn">Voltar</button>
  </div>

  <div class="game-screen hidden">
    <div class="game-info">
      <p>Moedas: <span id="coins">0</span></p>
      <p>Movimentos: <span id="moves">0</span></p>
      <p>Tempo: <span id="timer">00:00</span></p>
      <p>Progresso: <span id="progress">0%</span></p>
      <div class="progress-bar-container">
        <div class="progress-bar"></div>
      </div>
    </div>
    <div id="cards-grid"></div>
    <button id="back-to-difficulty-btn">Voltar</button>
  </div>

  <div class="result-screen hidden">
    <h1>Parabéns!</h1>
    <div id="stars"></div>
    <button id="continue-btn">Continuar</button>
    <button id="back-to-country-from-result-btn">Voltar ao Menu</button>
  </div>

  <audio id="flip-sound" src="https://grok3-audio.github.io/assets/audio/card-flip.mp3"></audio>
  <audio id="match-sound" src="https://grok3-audio.github.io/assets/audio/match-success.mp3"></audio>
  <audio id="error-sound" src="https://grok3-audio.github.io/assets/audio/error-buzz.mp3"></audio>
  <audio id="win-sound" src="https://grok3-audio.github.io/assets/audio/win-triumph.mp3"></audio>
  <audio id="background-music" src="https://grok3-audio.github.io/assets/audio/background-loop.mp3" loop></audio>

  <script src="script.js"></script>
</body>
</html>
```

### Your JavaScript

```javascript
const gameState = {
  coins: 0,
  currentCountry: null,
  currentDifficulty: null,
  flippedCards: [],
  matchedCards: [],
  moves: 0,
  time: 0,
  timerInterval: null,
  soundEffectsEnabled: true,
  backgroundMusicEnabled: true,
  failedImages: 0,
  failedAudios: 0,
  ranking: JSON.parse(localStorage.getItem('ranking')) || [],
};

const loadingScreen = document.querySelector('.loading-screen');
const loadingPercent = document.querySelector('.loading-percent');
const loadingError = document.querySelector('.loading-error');
const progressBar = document.querySelector('.loading-screen .progress-bar');
const countryScreen = document.querySelector('.country-screen');
const settingsScreen = document.querySelector('.settings-screen');
const skinsScreen = document.querySelector('.skins-screen');
const rankingScreen = document.querySelector('.ranking-screen');
const difficultyScreen = document.querySelector('.difficulty-screen');
const gameScreen = document.querySelector('.game-screen');
const resultScreen = document.querySelector('.result-screen');
const coinsDisplay = document.getElementById('coins');
const cardsGrid = document.getElementById('cards-grid');
const movesDisplay = document.getElementById('moves');
const timerDisplay = document.getElementById('timer');
const progressText = document.getElementById('progress');
const starsContainer = document.getElementById('stars');
const backgroundMusicToggle = document.getElementById('background-music-toggle');
const soundEffectsToggle = document.getElementById('sound-effects-toggle');
const flipSound = document.getElementById('flip-sound');
const matchSound = document.getElementById('match-sound');
const errorSound = document.getElementById('error-sound');
const winSound = document.getElementById('win-sound');
const backgroundMusic = document.getElementById('background-music');
const skipAudioBtn = document.getElementById('skip-audio-btn');

const FALLBACK_FLAG = 'https://picsum.photos/40/30?random=0';
const FALLBACK_IMAGE = 'https://picsum.photos/90/160?random=0';

const playersData = {
  england: {
    flag: 'https://flagcdn.com/40x30/gb.png',
    easy: [
      'https://i.ibb.co/8nwwFbL3/M-Salah-20250327-135508-0000.png',
      'https://i.ibb.co/GYSfYfr/9-20250327-184632-0008.png',
      'https://i.ibb.co/mC1W9PH5/8-20250327-184632-0007.png',
      'https://i.ibb.co/g2GZss3/7-20250327-184632-0006.png',
      'https://i.ibb.co/3mrzxBmm/5-20250327-184632-0004.png',
    ],
    medium: [
      'https://i.ibb.co/hJfbxDFw/6-20250330-154504-0005.png',
      'https://i.ibb.co/Ldy8M51T/5-20250330-154504-0004.png',
      'https://i.ibb.co/sp1kkJZw/4-20250330-154504-0003.png',
      'https://i.ibb.co/tMPDm1bZ/3-20250330-154504-0002.png',
      'https://i.ibb.co/Vc9MwJXr/2-20250330-154504-0001.png',
      'https://i.ibb.co/C5yP2TtM/1-20250330-154504-0000.png',
      'https://i.ibb.co/4rrXckj/15-20250330-154505-0014.png',
      'https://i.ibb.co/gL2bq4v2/14-20250330-154505-0013.png',
    ],
    hard: [
      'https://i.ibb.co/ZzBPZd6q/5-20250331-233216-0004.png',
      'https://i.ibb.co/5g2jdy8n/6-20250331-233217-0005.png',
      'https://i.ibb.co/Ps99N598/7-20250331-233217-0006.png',
      'https://i.ibb.co/TM5vfKLT/8-20250331-233217-0007.png',
      'https://i.ibb.co/RThPPNpD/9-20250331-233217-0008.png',
      'https://i.ibb.co/sdb070fV/10-20250331-233217-0009.png',
      'https://i.ibb.co/Gfc0wnMY/11-20250331-233217-0010.png',
      'https://i.ibb.co/PGqvGgD5/13-20250331-233217-0012.png',
      'https://i.ibb.co/20f2WwvY/12-20250331-233217-0011.png',
      'https://i.ibb.co/fVvLKwvy/15-20250331-233217-0014.png',
    ],
  },
  spain: {
    flag: 'https://flagcdn.com/40x30/es.png',
    easy: [
      'https://i.ibb.co/Vcxf67kB/1-20250329-161705-0000.png',
      'https://i.ibb.co/2YFLXG1W/3-20250329-161706-0002.png',
      'https://i.ibb.co/vxZbgycB/4-20250329-161706-0003.png',
      'https://i.ibb.co/cX2phCrZ/2-20250329-161706-0001.png',
      'https://i.ibb.co/sJPwN7Z1/5-20250329-161706-0004.png',
    ],
    medium: [
      'https://i.ibb.co/v6JvQpDZ/9-20250402-224936-0008.png',
      'https://i.ibb.co/GzWVRpr/8-20250402-224936-0007.png',
      'https://i.ibb.co/Kjbwjtjm/7-20250402-224936-0006.png',
      'https://i.ibb.co/Z1wSVv60/6-20250402-224936-0005.png',
      'https://i.ibb.co/qMjPQ64p/5-20250402-224936-0004.png',
      'https://i.ibb.co/PyFhWsv/4-20250402-224936-0003.png',
      'https://i.ibb.co/d0Tr1Bcp/2-20250402-224936-0001.png',
      'https://i.ibb.co/mVm18s1H/3-20250402-224936-0002.png',
    ],
    hard: [
      'https://i.ibb.co/1GnSrFht/8-20250403-123010-0007.png',
      'https://i.ibb.co/HL4XHWWV/7-20250403-123010-0006.png',
      'https://i.ibb.co/TXZpjmV/9-20250403-123010-0008.png',
      'https://i.ibb.co/jPZbTKW0/10-20250403-123010-0009.png',
      'https://i.ibb.co/KjTZKVhg/6-20250403-123009-0005.png',
      'https://i.ibb.co/7yLRBRy/14-20250403-123010-0013.png',
      'https://i.ibb.co/7JgJHN0k/11-20250403-123010-0010.png',
      'https://i.ibb.co/RT9JcScx/12-20250403-123010-0011.png',
      'https://i.ibb.co/NdWSphfc/13-20250403-123010-0012.png',
      'https://i.ibb.co/XkWbJtDH/15-20250403-123010-0014.png',
    ],
  },
  brazil: {
    flag: 'https://flagcdn.com/40x30/br.png',
    easy: [
      'https://picsum.photos/90/160?random=1',
      'https://i.ibb.co/gK3vspq/10-20250328-175749-0009.png',
      'https://i.ibb.co/S2TB09h/1-20250328-175748-0000.png',
      'https://picsum.photos/90/160?random=2',
      'https://i.ibb.co/JWshTJYR/8-20250328-175749-0007.png',
    ],
    medium: [
      'https://i.ibb.co/9m3hnP2x/15-20250404-133205-0014.png',
      'https://i.ibb.co/kgj5GFMR/2-20250404-133205-0001.png',
      'https://i.ibb.co/TqPcdjDX/3-20250404-133205-0002.png',
      'https://i.ibb.co/TDPyYwpY/6-20250404-133205-0005.png',
      'https://i.ibb.co/p7Y7rZk/5-20250404-133205-0004.png',
      'https://picsum.photos/90/160?random=3',
      'https://i.ibb.co/d0kBZJj9/8-20250404-133205-0007.png',
      'https://i.ibb.co/3qVJ5K8/7-20250404-133205-0006.png',
    ],
    hard: [
      'https://i.ibb.co/gbwLWBHG/20-20250405-101452-0019.png',
      'https://i.ibb.co/YThYd458/2-20250405-101451-0001.png',
      'https://i.ibb.co/Tq2tssPy/3-20250405-101451-0002.png',
      'https://i.ibb.co/PvM4cz4r/4-20250405-101451-0003.png',
      'https://i.ibb.co/Hf15SXnC/5-20250405-101451-0004.png',
      'https://i.ibb.co/zhTcWw38/6-20250405-101451-0005.png',
      'https://i.ibb.co/SwVMTkcs/13-20250405-101451-0012.png',
      'https://i.ibb.co/Tn4tHr4/12-20250405-101451-0011.png',
      'https://i.ibb.co/hRB3n62p/11-20250405-101451-0010.png',
      'https://i.ibb.co/Xx9BzL2Q/9-20250405-101451-0008.png',
    ],
  },
};

let imageProgress = 0;
let audioProgress = 0;
let totalImages = 0;
let totalAudios = 0;
let skipAudios = false;

function loadImage(src) {
  return new Promise((resolve) => {
    const img = new Image();
    img.src = src;
    img.onload = () => {
      console.log(`Imagem carregada: ${src}`);
      resolve();
    };
    img.onerror = () => {
      console.error(`Erro ao carregar imagem: ${src}`);
      gameState.failedImages++;
      console.log(`Total de imagens com falha: ${gameState.failedImages}`);
      resolve();
    };
  });
}

async function loadAudio(src, retries = 2) {
  for (let attempt = 1; attempt <= retries + 1; attempt++) {
    try {
      console.log(`Tentativa ${attempt} de carregar áudio: ${src}`);
      const audio = new Audio();
      audio.src = src;
      audio.preload = 'auto';

      await new Promise((resolve, reject) => {
        audio.addEventListener('loadedmetadata', () => {
          console.log(`Metadados carregados para: ${src}`);
          resolve();
        }, { once: true });
        audio.onerror = (e) => {
          const errorMsg = `Erro ao carregar áudio: ${src} (code: ${e.target.error?.code || 'desconhecido'}, message: ${e.target.error?.message || 'desconhecido'})`;
          console.error(errorMsg);
          reject(new Error(errorMsg));
        };
        setTimeout(() => {
          console.error(`Timeout ao carregar áudio: ${src}`);
          reject(new Error(`Timeout ao carregar áudio: ${src}`));
        }, 10000);
      });

      console.log(`Áudio ${src} carregado com sucesso`);
      return audio;
    } catch (error) {
      console.error(`Tentativa ${attempt} falhou para ${src}: ${error.message}`);
      if (attempt > retries) {
        gameState.failedAudios++;
        console.log(`Total de áudios com falha: ${gameState.failedAudios}`);
        throw error;
      }
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }
  }
}

async function loadResources() {
  console.log('Iniciando loadResources');
  
  console.log('Verificando elementos do DOM:');
  console.log('loadingScreen:', !!loadingScreen);
  console.log('countryScreen:', !!countryScreen);
  console.log('loadingPercent:', !!loadingPercent);
  console.log('progressBar:', !!progressBar);
  console.log('loadingError:', !!loadingError);
  console.log('flipSound:', !!flipSound, 'src:', flipSound?.src);
  console.log('matchSound:', !!matchSound, 'src:', matchSound?.src);
  console.log('errorSound:', !!errorSound, 'src:', errorSound?.src);
  console.log('winSound:', !!winSound, 'src:', winSound?.src);
  console.log('backgroundMusic:', !!backgroundMusic, 'src:', backgroundMusic?.src);

  const images = [
    playersData.england.flag,
    playersData.spain.flag,
    playersData.brazil.flag,
    ...playersData.england.easy,
    ...playersData.spain.easy,
    ...playersData.brazil.easy,
  ];
  const audios = [
    flipSound?.src,
    matchSound?.src,
    errorSound?.src,
    winSound?.src,
    backgroundMusic?.src,
  ].filter(Boolean);

  totalImages = images.length;
  totalAudios = audios.length;
  console.log(`Total de imagens (Fácil + bandeiras): ${totalImages}, Total de áudios: ${totalAudios}`);

  try {
    let totalResources = totalImages + totalAudios;
    let loadedResources = 0;

    const imagePromises = images.map(async (src) => {
      await loadImage(src);
      loadedResources++;
      imageProgress = (loadedResources / totalResources) * 100;
      console.log(`imageProgress: ${imageProgress.toFixed(2)}%`);
      if (progressBar) progressBar.style.width = `${imageProgress}%`;
      if (loadingPercent) loadingPercent.textContent = `${Math.round(imageProgress)}%`;
    });
    await Promise.allSettled(imagePromises);
    console.log('Imagens (Fácil + bandeiras) carregadas');

    if (!skipAudios) {
      const audioPromises = audios.map(async (src) => {
        const audio = await loadAudio(src);
        loadedResources++;
        audioProgress = (loadedResources / totalResources) * 100;
        console.log(`audioProgress: ${audioProgress.toFixed(2)}%`);
        if (progressBar) progressBar.style.width = `${audioProgress}%`;
        if (loadingPercent) loadingPercent.textContent = `${Math.round(audioProgress)}%`;
      });
      await Promise.all(audioPromises);
      console.log('Áudios carregados com sucesso');
    } else {
      console.warn('Carregamento de áudios pulado');
      loadedResources += totalAudios;
      audioProgress = 100;
      if (progressBar) progressBar.style.width = '100%';
      if (loadingPercent) loadingPercent.textContent = '100%';
    }

    if (gameState.failedImages > 0 && loadingError) {
      console.log(`Aviso: ${gameState.failedImages} imagens falharam, prosseguindo com fallback`);
      loadingError.textContent = `Aviso: ${gameState.failedImages} imagens não carregaram. Usando imagens reserva.`;
      loadingError.classList.remove('hidden');
      setTimeout(() => {
        if (loadingError) loadingError.classList.add('hidden');
      }, 3000);
    }

    if (loadingScreen && countryScreen) {
      console.log('Transitando para country-screen');
      loadingScreen.classList.add('hidden');
      countryScreen.classList.remove('hidden');
      playBackgroundMusic();
      loadRemainingImages();
    } else {
      console.error('Erro: loadingScreen ou countryScreen não encontrados no DOM');
      if (loadingError) {
        loadingError.textContent = 'Erro: Estrutura da página inválida. Contate o suporte.';
        loadingError.classList.remove('hidden');
      }
    }
  } catch (error) {
    console.error('Erro durante loadResources:', error.message);
    if (loadingError) {
      loadingError.textContent = `Erro ao carregar áudios: ${error.message}. Verifique sua conexão e tente novamente.`;
      loadingError.classList.remove('hidden');
      if (skipAudioBtn) {
        skipAudioBtn.classList.remove('hidden');
      }
    }
  }
}

async function loadRemainingImages() {
  console.log('Iniciando loadRemainingImages');
  const remainingImages = [
    ...playersData.england.medium,
    ...playersData.england.hard,
    ...playersData.spain.medium,
    ...playersData.spain.hard,
    ...playersData.brazil.medium,
    ...playersData.brazil.hard,
  ];
  console.log(`Total de imagens restantes (Médio + Difícil): ${remainingImages.length}`);

  for (const src of remainingImages) {
    try {
      await loadImage(src);
      console.log(`Imagem restante carregada: ${src}`);
    } catch {
      console.error(`Erro ao carregar imagem restante: ${src}`);
      gameState.failedImages++;
      console.log(`Total de imagens com falha: ${gameState.failedImages}`);
    }
  }
  console.log('Carregamento de imagens restantes concluído');
}

function playBackgroundMusic() {
  if (gameState.backgroundMusicEnabled && backgroundMusic) {
    console.log('Tentando tocar música de fundo');
    backgroundMusic.play().catch((e) => {
      console.warn('Música de fundo bloqueada:', e.message);
      gameState.backgroundMusicEnabled = false;
      if (backgroundMusicToggle) backgroundMusicToggle.checked = false;
      saveSettings();
    });
  } else {
    console.warn('backgroundMusic não encontrado ou desativado');
  }
}

function shuffle(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
}

function createCard(image) {
  const card = document.createElement('div');
  card.classList.add('card');
  card.dataset.image = image;

  const cardBack = document.createElement('div');
  cardBack.classList.add('card-back');
  cardBack.textContent = '?';

  const cardFront = document.createElement('div');
  cardFront.classList.add('card-front');
  const img = document.createElement('img');
  img.src = image;
  img.alt = 'Player';
  img.onerror = () => {
    img.src = FALLBACK_IMAGE;
    console.warn(`Imagem da carta ${image} falhou, usando fallback`);
  };
  cardFront.appendChild(img);

  card.appendChild(cardBack);
  card.appendChild(cardFront);

  card.addEventListener('click', () => flipCard(card));
  return card;
}

function startGame(difficulty) {
  console.log(`Iniciando jogo: ${gameState.currentCountry}, dificuldade: ${difficulty}`);
  gameState.currentDifficulty = difficulty;
  gameState.flippedCards = [];
  gameState.matchedCards = [];
  gameState.moves = 0;
  gameState.time = 0;
  movesDisplay.textContent = '0';
  timerDisplay.textContent = '00:00';
  progressText.textContent = '0%';
  cardsGrid.innerHTML = '';

  let images = playersData[gameState.currentCountry][difficulty].slice();
  images = [...images, ...images];
  images = shuffle(images);

  const cardCount = images.length;
  cardsGrid.style.gridTemplateColumns = `repeat(${Math.ceil(Math.sqrt(cardCount))}, 1fr)`;

  images.forEach((image) => {
    const card = createCard(image);
    cardsGrid.appendChild(card);
  });

  if (gameState.timerInterval) clearInterval(gameState.timerInterval);
  gameState.timerInterval = setInterval(updateTimer, 1000);

  if (gameState.backgroundMusicEnabled && backgroundMusic && backgroundMusic.paused) {
    console.log('Tentando retomar música de fundo ao iniciar partida');
    backgroundMusic.play().catch((e) => console.warn('Música de fundo bloqueada ao iniciar partida:', e.message));
  }

  difficultyScreen.classList.add('hidden');
  gameScreen.classList.remove('hidden');

  setTimeout(() => {
    cardsGrid.querySelectorAll('.card').forEach((card) => {
      card.classList.add('shuffling');
      setTimeout(() => card.classList.remove('shuffling'), 2000);
    });
  }, 100);
}

function flipCard(card) {
  if (
    gameState.flippedCards.length < 2 &&
    !gameState.flippedCards.includes(card) &&
    !gameState.matchedCards.includes(card)
  ) {
    card.classList.add('flipped');
    gameState.flippedCards.push(card);
    if (gameState.soundEffectsEnabled && flipSound && !skipAudios) {
      flipSound.currentTime = 0;
      flipSound.play().catch((e) => console.warn('Erro ao tocar flipSound:', e.message));
    }

    if (gameState.flippedCards.length === 2) {
      gameState.moves++;
      movesDisplay.textContent = gameState.moves;
      checkMatch();
    }
  }
}

function checkMatch() {
  const [card1, card2] = gameState.flippedCards;
  if (card1.dataset.image === card2.dataset.image) {
    card1.classList.add('effect-sparkles', 'pulse');
    card2.classList.add('effect-sparkles', 'pulse');
    gameState.matchedCards.push(card1, card2);
    gameState.flippedCards = [];
    if (gameState.soundEffectsEnabled && matchSound && !skipAudios) {
      matchSound.currentTime = 0;
      matchSound.play().catch((e) => console.warn('Erro ao tocar matchSound:', e.message));
    }

    const progress = (gameState.matchedCards.length / cardsGrid.children.length) * 100;
    progressText.textContent = `${Math.round(progress)}%`;
    gameScreen.querySelector('.progress-bar').style.width = `${progress}%`;

    if (gameState.matchedCards.length === cardsGrid.children.length) {
      endGame();
    }
  } else {
    card1.classList.add('shake');
    card2.classList.add('shake');
    setTimeout(() => {
      card1.classList.remove('flipped', 'shake');
      card2.classList.remove('flipped', 'shake');
      gameState.flippedCards = [];
      if (gameState.soundEffectsEnabled && errorSound && !skipAudios) {
        if (matchSound) matchSound.pause();
        errorSound.currentTime = 0;
        errorSound.play().catch((e) => console.warn('Erro ao tocar errorSound:', e.message));
      }
    }, 800);
  }
}

function updateTimer() {
  gameState.time++;
  const minutes = Math.floor(gameState.time / 60);
  const seconds = gameState.time % 60;
  timerDisplay.textContent = `${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
}

function calculateStars() {
  const maxMoves = { easy: 15, medium: 30, hard: 50 };
  const maxTime = { easy: 60, medium: 120, hard: 180 };
  const movesRatio = gameState.moves / maxMoves[gameState.currentDifficulty];
  const timeRatio = gameState.time / maxTime[gameState.currentDifficulty];
  const score = 3 - Math.floor((movesRatio + timeRatio) * 1.5);
  return Math.max(1, Math.min(3, score));
}

function endGame() {
  clearInterval(gameState.timerInterval);
  const stars = calculateStars();
  starsContainer.innerHTML = '?'.repeat(stars);
  gameState.coins += stars * 10;
  coinsDisplay.textContent = gameState.coins;
  saveSettings();
  if (gameState.soundEffectsEnabled && winSound && !skipAudios) {
    winSound.play().catch((e) => console.warn('Erro ao tocar winSound:', e.message));
  }
  confetti({
    particleCount: 100,
    spread: 70,
    origin: { y: 0.6 },
  });
  gameScreen.classList.add('hidden');
  resultScreen.classList.remove('hidden');
}

function saveSettings() {
  localStorage.setItem('gameState', JSON.stringify({
    coins: gameState.coins,
    soundEffectsEnabled: gameState.soundEffectsEnabled,
    backgroundMusicEnabled: gameState.backgroundMusicEnabled,
  }));
}

function loadSettings() {
  const savedState = JSON.parse(localStorage.getItem('gameState'));
  if (savedState) {
    gameState.coins = savedState.coins || 0;
    gameState.soundEffectsEnabled = savedState.soundEffectsEnabled !== false;
    gameState.backgroundMusicEnabled = savedState.backgroundMusicEnabled !== false;
    coinsDisplay.textContent = gameState.coins;
    if (backgroundMusicToggle) backgroundMusicToggle.checked = gameState.backgroundMusicEnabled;
    if (soundEffectsToggle) soundEffectsToggle.checked = gameState.soundEffectsEnabled;
  }
}

document.querySelectorAll('.country-btn').forEach((button) => {
  button.addEventListener('click', () => {
    if (!button.disabled) {
      gameState.currentCountry = button.dataset.country;
      countryScreen.classList.add('hidden');
      difficultyScreen.classList.remove('hidden');
    }
  });
});

document.querySelectorAll('.difficulty-btn').forEach((button) => {
  button.addEventListener('click', () => startGame(button.dataset.difficulty));
});

document.getElementById('settings-btn').addEventListener('click', () => {
  countryScreen.classList.add('hidden');
  settingsScreen.classList.remove('hidden');
});

document.getElementById('skins-btn').addEventListener('click', () => {
  countryScreen.classList.add('hidden');
  skinsScreen.classList.remove('hidden');
});

document.getElementById('ranking-btn').addEventListener('click', () => {
  countryScreen.classList.add('hidden');
  rankingScreen.classList.remove('hidden');
});

document.getElementById('back-to-country-btn').addEventListener('click', () => {
  settingsScreen.classList.add('hidden');
  countryScreen.classList.remove('hidden');
});

document.getElementById('back-to-country-from-skins-btn').addEventListener('click', () => {
  skinsScreen.classList.add('hidden');
  countryScreen.classList.remove('hidden');
});

document.getElementById('back-to-country-from-ranking-btn').addEventListener('click', () => {
  rankingScreen.classList.add('hidden');
  countryScreen.classList.remove('hidden');
});

document.getElementById('back-to-country-from-difficulty-btn').addEventListener('click', () => {
  difficultyScreen.classList.add('hidden');
  countryScreen.classList.remove('hidden');
});

document.getElementById('back-to-difficulty-btn').addEventListener('click', () => {
  clearInterval(gameState.timerInterval);
  gameScreen.classList.add('hidden');
  difficultyScreen.classList.remove('hidden');
});

document.getElementById('continue-btn').addEventListener('click', () => {
  resultScreen.classList.add('hidden');
  difficultyScreen.classList.remove('hidden');
});

document.getElementById('back-to-country-from-result-btn').addEventListener('click', () => {
  resultScreen.classList.add('hidden');
  countryScreen.classList.remove('hidden');
});

backgroundMusicToggle.addEventListener('change', () => {
  gameState.backgroundMusicEnabled = backgroundMusicToggle.checked;
  if (gameState.backgroundMusicEnabled && backgroundMusic && !skipAudios) {
    console.log('Música de fundo ativada pelo toggle');
    backgroundMusic.play().catch((e) => {
      console.warn('Música de fundo bloqueada pelo toggle:', e.message);
      gameState.backgroundMusicEnabled = false;
      backgroundMusicToggle.checked = false;
    });
  } else if (backgroundMusic) {
    console.log('Música de fundo pausada pelo toggle');
    backgroundMusic.pause();
  }
  saveSettings();
});

soundEffectsToggle.addEventListener('change', () => {
  gameState.soundEffectsEnabled = soundEffectsToggle.checked;
  saveSettings();
});

document.querySelectorAll('.skin-btn').forEach((button) => {
  button.addEventListener('click', () => {
    if (!button.querySelector('.locked-overlay')) {
      document.body.className = `background-${button.dataset.skin}`;
    }
  });
});

if (skipAudioBtn) {
  skipAudioBtn.addEventListener('click', () => {
    skipAudios = true;
    console.log('Botão "Pular Áudios" clicado');
    if (loadingError) {
      loadingError.textContent = 'Áudios pulados. Prosseguindo...';
    }
    loadResources();
  });
}

document.addEventListener('click', () => {
  if (gameState.backgroundMusicEnabled && backgroundMusic && backgroundMusic.paused && !skipAudios) {
    console.log('Tentando desbloquear música de fundo com clique');
    backgroundMusic.play().catch((e) => console.warn('Música de fundo bloqueada mesmo após clique:', e.message));
  }
}, { once: true });

document.addEventListener('DOMContentLoaded', () => {
  console.log('DOM carregado, iniciando inicialização');
  loadSettings();
  loadResources();
});
```

### Your CSS

```css
body {
  margin: 0;
  font-family: Arial, sans-serif;
  background: linear-gradient(to bottom, #1a3c34, #2a5d52);
  color: #fff;
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  overflow-y: auto;
}

.background-default { background: linear-gradient(to bottom, #1a3c34, #2a5d52); }
.background-dark { background: linear-gradient(to bottom, #121212, #1e1e1e); }
.background-stadium { background: url('https://picsum.photos/1920/1080?random=1') no-repeat center/cover; }

.hidden { display: none !important; }

.loading-screen, .country-screen, .settings-screen, .skins-screen, .ranking-screen, .difficulty-screen, .game-screen, .result-screen {
  text-align: center;
  padding: 20px;
  max-width: 800px;
  width: 100%;
  box-sizing: border-box;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
}

.loading-screen { background: rgba(0, 0, 0, 0.8); }
.country-screen, .settings-screen, .skins-screen, .ranking-screen, .difficulty-screen, .game-screen, .result-screen {
  display: none;
}

.country-screen:not(.hidden), .settings-screen:not(.hidden), .skins-screen:not(.hidden), 
.ranking-screen:not(.hidden), .difficulty-screen:not(.hidden), .game-screen:not(.hidden), 
.result-screen:not(.hidden) {
  display: flex;
  opacity: 0;
  transform: translateX(20px);
  animation: slideIn 0.5s ease-out forwards;
}

@keyframes slideIn {
  to { opacity: 1; transform: translateX(0); }
}

.progress-bar-container {
  width: 80%;
  height: 20px;
  background: #333;
  border-radius: 10px;
  overflow: hidden;
  margin: 10px 0;
}

.progress-bar {
  height: 100%;
  background: linear-gradient(to right, #4caf50, #81c784);
  width: 0;
  transition: width 0.3s ease;
}

.loading-error {
  color: #ff4444;
  margin-top: 10px;
  font-size: 0.9em;
}

button {
  padding: 10px 20px;
  margin: 10px;
  font-size: 1.1em;
  background: #4caf50;
  color: #fff;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  transition: background 0.3s, transform 0.2s;
}

button:hover { background: #45a049; transform: scale(1.05); }
button:focus { outline: 2px solid #fff; outline-offset: 2px; }
button:disabled { background: #666; cursor: not-allowed; }

.country-btn, .difficulty-btn, .skin-btn {
  width: 200px;
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
}

.locked-overlay {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.7);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 1.5em;
}

#cards-grid {
  display: grid;
  gap: 10px;
  width: 100%;
  max-width: 600px;
  margin: 20px auto;
}

.card {
  aspect-ratio: 9 / 16;
  background: #fff;
  border-radius: 10px;
  position: relative;
  cursor: pointer;
  transform-style: preserve-3d;
  transition: transform 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55);
}

.card-back, .card-front {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  backface-visibility: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 10px;
}

.card-back {
  background: linear-gradient(45deg, #0288d1, #4fc3f7);
  font-size: 2em;
}

.card-front {
  transform: rotateY(180deg);
  background: #fff;
}

.card-front img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  border-radius: 10px;
}

.card.flipped {
  transform: rotateY(180deg);
}

.card.shuffling {
  animation: shuffle 2s ease-in-out;
}

@keyframes shuffle {
  0%, 100% { transform: translate(0, 0); recyclable: true }
  25% { transform: translate(10px, -10px) rotate(5deg); }
  50% { transform: translate(-10px, 10px) rotate(-5deg); }
  75% { transform: translate(5px, -5px) rotate(3deg); }
}

.card.effect-sparkles {
  position: relative;
}

.card.effect-sparkles::before {
  content: '✨';
  position: absolute;
  font-size: 1.5em;
  animation: floatStars 1s ease-out forwards;
}

@keyframes floatStars {
  0% { transform: translateY(0); opacity: 1; }
  100% { transform: translateY(-20px); opacity: 0; }
}

.card.pulse {
  animation: pulse 0.5s ease-in-out;
}

@keyframes pulse {
  0%, 100% { transform: scale(1); }
  50% { transform: scale(1.1); }
}

.card.shake {
  animation: shake 0.5s ease-in-out;
}

@keyframes shake {
  0%, 100% { transform: translateX(0); }
  25% { transform: translateX(-5px); }
  75% { transform: translateX(5px); }
}

.result-screen h1 {
  animation: zoomIn 0.5s ease-out;
}

@keyframes zoomIn {
  0% { transform: scale(0.5); opacity: 0; }
  100% { transform: scale(1); opacity: 1; }
}

@media (max-width: 600px) {
  h1 { font-size: 1.5em; }
  button { font-size: 1em; padding: 8px 16px; }
  #cards-grid { gap: 5px; }
  .card-back { font-size: 1.5em; }
}
```
