### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by faizlzm** [jsfiddle/jsfiddle-users#2018]
### Error code

ERRW:1.0:K1.0

### Were you logged in?

Yes

### Your username (if logged in)

faizlzm

### Your HTML

```html
<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Sandal Vending Machine</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div class="vending-machine">
    <div class="header">
      <h1>Sandal Vending Machine</h1>
    </div>
    
    <div class="display" id="display" role="alert" aria-live="polite">Selamat Datang</div>

    <div id="idle-screen">
      <p>Tekan tombol di bawah untuk mulai berbelanja sandal!</p>
      <button id="start-button" class="start-button">Mulai Belanja</button>
    </div>

    <div id="selection-screen" style="display: none;">
      <div class="section-title">
        <h3>Pilih Sandal Anda</h3>
      </div>
      
      <div class="product-grid">
        <button class="product" tabindex="0" data-id="1" data-price="10" data-name="Sandal Pantai" aria-label="Pilih Sandal Pantai seharga Rp.10.000">
          <h4>Sandal Pantai</h4>
          <p>Rp.10.000</p>
        </button>
        <button class="product" tabindex="0" data-id="2" data-price="15" data-name="Sandal Nyaman" aria-label="Pilih Sandal Nyaman seharga Rp.15.000">
          <h4>Sandal Nyaman</h4>
          <p>Rp.15.000</p>
        </button>
        <button class="product" tabindex="0" data-id="3" data-price="20" data-name="Sandal Olahraga" aria-label="Pilih Sandal Olahraga seharga Rp.20.000">
          <h4>Sandal Olahraga</h4>
          <p>Rp.20.000</p>
        </button>
        <button class="product" tabindex="0" data-id="4" data-price="25" data-name="Sandal Kulit Mewah" aria-label="Pilih Sandal Kulit Mewah seharga Rp.25.000">
          <h4>Sandal Kulit Mewah</h4>
          <p>Rp.25.000</p>
        </button>
      </div>
    
      <div class="section-title">
        <h3>Pembayaran</h3>
      </div>
      
      <div class="money-status">
        <div>Uang Dimasukkan: <strong>Rp.<span id="inserted-amount">0</span></strong></div>
        <div>Dipilih: <strong><span id="selected-item">Tidak Ada</span></strong></div>
      </div>
      
      <p>Masukkan koin dengan mengklik di bawah ini:</p>
      <div class="coins">
        <button class="coin" tabindex="0" data-value="1" aria-label="Masukkan Rp.1.000">Rp.1k</button>
        <button class="coin" tabindex="0" data-value="5" aria-label="Masukkan Rp.5.000">Rp.5k</button>
        <button class="coin" tabindex="0" data-value="10" aria-label="Masukkan Rp.10.000">Rp.10k</button>
      </div>
    
      <div class="button-group">
        <button id="purchase-button" class="purchase-button" disabled>Beli</button>
        <button id="cancel-button" class="cancel-button">Batal</button>
      </div>
    </div>

    <div class="dispensed" id="dispensed">
      Produk Anda akan muncul di sini
    </div>

    <div class="machine-state">
      <div>Status Mesin: <span id="current-state">idle</span></div>
      <div>Konteks: <span id="context-data">{}</span></div>
    </div>
  </div>
  <script src="https://unpkg.com/xstate@4.37.1/dist/xstate.js"></script>
  <script src="script.js"></script>
</body>
</html>
```

### Your JavaScript

```javascript
document.addEventListener('DOMContentLoaded', () => {
  const vendingMachineConfig = {
    id: 'slipperVendingMachine',
    initial: 'idle',
    context: {
      insertedMoney: 0,
      selectedItem: null,   
      change: 0
    },
    states: {
      idle: {
        entry: 'resetMachine',
        on: { START: 'selecting' }
      },
      selecting: {
        entry: 'showSelectionScreen',
        on: {
          SELECT_ITEM: { actions: 'setSelectedItem' },
          INSERT_MONEY: { actions: 'addMoney' },
          PURCHASE: { target: 'dispensing', cond: 'hasSufficientFunds' },
          CANCEL: { target: 'returning', actions: 'calculateChange' }
        }
      },
      dispensing: {
        entry: 'displayDispensingMessage',
        after: {
          2000: { target: 'returning', actions: ['dispenseItem', 'calculateChange'] }
        }
      },
      returning: {
        entry: 'displayReturningChange',
        after: {
          2000: { target: 'idle', actions: 'dispenseChange' }
        }
      }
    }
  };

  const vendingMachineOptions = {
    actions: {
      resetMachine: (context) => {
        context.insertedMoney = 0;
        context.selectedItem = null;
        context.change = 0;
        showScreen('idle-screen');
        updateDisplay('Selamat Datang di Sandal Vending Machine!');
        resetDispensed();
        updateInsertedAmount(0);
        updateSelectedItem('Tidak Ada');
        disablePurchaseButton();
        clearSelectedProducts();
      },
      showSelectionScreen: () => {
        showScreen('selection-screen');
        updateDisplay('Silakan pilih produk dan masukkan uang');
      },
      setSelectedItem: (context, event) => {
        context.selectedItem = { id: event.id, name: event.name, price: event.price };
        updateSelectedItem(event.name);
        highlightSelectedProduct(event.id);
        updateDisplay(`Dipilih: ${event.name} - Rp${event.price}.000`);
        if (context.insertedMoney < event.price) {
          updateDisplay(`Dipilih: ${event.name} - Rp${event.price}.000. Perlu Rp${(event.price - context.insertedMoney)}.000 lagi`);
          disablePurchaseButton();
        } else {
          updateDisplay(`Dipilih: ${event.name} - Siap untuk dibeli!`);
          enablePurchaseButton();
        }
      },
      addMoney: (context, event) => {
        context.insertedMoney += event.amount;
        updateInsertedAmount(context.insertedMoney);
        if (context.selectedItem) {
          const remaining = context.selectedItem.price - context.insertedMoney;
          if (remaining > 0) {
            updateDisplay(`Ditambahkan Rp${event.amount}.000. Total: Rp${context.insertedMoney}.000. Perlu Rp${remaining}.000 lagi`);
            disablePurchaseButton();
          } else {
            updateDisplay(`Ditambahkan Rp${event.amount}.000. Siap untuk dibeli!`);
            enablePurchaseButton();
          }
        } else {
          updateDisplay(`Ditambahkan Rp${event.amount}.000. Total: Rp${context.insertedMoney}.000`);
        }
      },
      calculateChange: (context) => {
        context.change = context.selectedItem ? Math.max(0, context.insertedMoney - context.selectedItem.price) : context.insertedMoney;
      },
      displayDispensingMessage: (context) => {
        updateDisplay(`Mengeluarkan ${context.selectedItem.name}...`);
      },
      dispenseItem: (context) => {
        document.getElementById('dispensed').innerHTML = `<h3>Ini ${context.selectedItem.name} Anda!</h3>`;
      },
      displayReturningChange: (context) => {
        if (context.change > 0) {
          updateDisplay(`Transaksi selesai. Mengembalikan kembalian: Rp${context.change}.000`);
        } else {
          updateDisplay('Terima kasih atas pembelian Anda!');
        }
      },
      dispenseChange: (context) => {
        if (context.change > 0) {
          document.getElementById('dispensed').innerHTML += `<div>Kembalian: Rp${context.change}.000</div>`;
        }
      }
    },
    guards: {
      hasSufficientFunds: (context) => context.selectedItem && context.insertedMoney >= context.selectedItem.price
    }
  };

  const vendingMachine = XState.Machine(vendingMachineConfig, vendingMachineOptions);
  const service = XState.interpret(vendingMachine)
    .onTransition(state => {
      document.getElementById('current-state').textContent = state.value;
      document.getElementById('context-data').textContent = JSON.stringify({
        insertedMoney: state.context.insertedMoney,
        selectedItem: state.context.selectedItem?.name || 'Tidak Ada',
        change: state.context.change
      }, null, 2);
    })
    .start();

  document.getElementById('start-button').addEventListener('click', () => service.send('START'));
  document.querySelectorAll('.product').forEach(el => {
    el.addEventListener('click', () => {
      service.send({ type: 'SELECT_ITEM', id: el.dataset.id, name: el.dataset.name, price: parseFloat(el.dataset.price) });
    });
  });
  document.querySelectorAll('.coin').forEach(el => {
    el.addEventListener('click', () => {
      service.send({ type: 'INSERT_MONEY', amount: parseFloat(el.dataset.value) });
    });
  });
  document.getElementById('purchase-button').addEventListener('click', () => service.send('PURCHASE'));
  document.getElementById('cancel-button').addEventListener('click', () => service.send('CANCEL'));

  // Helper Functions
  function showScreen(screenId) {
    document.getElementById('idle-screen').style.display = 'none';
    document.getElementById('selection-screen').style.display = 'none';
    document.getElementById(screenId).style.display = 'block';
  }
  function updateDisplay(message) {
    document.getElementById('display').textContent = message;
  }
  function updateInsertedAmount(amount) {
    document.getElementById('inserted-amount').textContent = amount + '.000';
  }
  function updateSelectedItem(name) {
    document.getElementById('selected-item').textContent = name;
  }
  function resetDispensed() {
    document.getElementById('dispensed').textContent = 'Produk Anda akan muncul di sini';
  }
  function enablePurchaseButton() {
    document.getElementById('purchase-button').disabled = false;
  }
  function disablePurchaseButton() {
    document.getElementById('purchase-button').disabled = true;
  }
  function clearSelectedProducts() {
    document.querySelectorAll('.product').forEach(el => el.classList.remove('selected'));
  }
  function highlightSelectedProduct(id) {
    clearSelectedProducts();
    document.querySelectorAll('.product').forEach(el => {
      if (el.dataset.id === id) el.classList.add('selected');
    });
  }
});
```

### Your CSS

```css
:root {
    --primary-color: #4285F4;
    --primary-dark: #3367d6;
    --success-color: #34A853;
    --warning-color: #FBBC05;
    --danger-color: #EA4335;
    --neutral-color: #F5F5F5;
    --text-color: #333333;
    --text-light: #666666;
    --border-radius: 8px;
    --box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    --transition: all 0.3s ease;
  }
  
  body {
    font-family: 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
    max-width: 550px;
    margin: 0 auto;
    padding: 20px;
    background-color: #f9f9f9;
    color: var(--text-color);
    line-height: 1.6;
  }
  
  h1, h2, h3, h4 {
    color: var(--text-color);
    margin-top: 0;
  }
  
  .vending-machine {
    border: none;
    border-radius: var(--border-radius);
    padding: 25px;
    background-color: #fff;
    box-shadow: var(--box-shadow);
    overflow: hidden;
  }
  
  .header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 20px;
    border-bottom: 2px solid var(--neutral-color);
    padding-bottom: 10px;
  }
  
  .header h1 {
    font-size: 1.8rem;
    margin: 0;
  }
  
  .logo {
    font-size: 24px;
    color: var(--primary-color);
    margin-right: 10px;
  }
  
  .display {
    background-color: #2c2c2c;
    color: #3cff3c;
    font-family: 'Courier New', monospace;
    padding: 15px;
    border-radius: var(--border-radius);
    margin-bottom: 25px;
    min-height: 20px;
    font-size: 1.1rem;
    text-align: center;
    box-shadow: inset 0 2px 4px rgba(0,0,0,0.2);
  }
  
  .product-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 15px;
    margin-bottom: 25px;
  }
  
  .product {
    border: 2px solid #e0e0e0;
    padding: 15px;
    border-radius: var(--border-radius);
    cursor: pointer;
    background-color: #fff;
    transition: var(--transition);
    text-align: center;
    height: 100%;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
  }
  
  .product:hover {
    border-color: var(--primary-color);
    box-shadow: 0 2px 8px rgba(66, 133, 244, 0.15);
  }
  
  .product.selected {
    border-color: var(--primary-color);
    background-color: rgba(66, 133, 244, 0.05);
    box-shadow: 0 2px 8px rgba(66, 133, 244, 0.15);
  }
  
  .product h4 {
    margin: 0 0 10px 0;
    font-size: 1.2rem;
  }
  
  .product p {
    margin: 0;
    font-weight: bold;
    color: var(--primary-color);
    font-size: 1.1rem;
  }
  
  .section-title {
    margin-top: 30px;
    margin-bottom: 15px;
    display: flex;
    align-items: center;
  }
  
  .section-title .icon {
    margin-right: 10px;
    color: var(--primary-color);
  }
  
  .money-status {
    background-color: var(--neutral-color);
    padding: 12px 15px;
    border-radius: var(--border-radius);
    display: flex;
    justify-content: space-between;
    margin-bottom: 15px;
    font-weight: 500;
  }
  
  .coins {
    display: flex;
    gap: 15px;
    margin-bottom: 25px;
    justify-content: center;
  }
  
  .coin {
    width: 60px;
    height: 60px;
    border-radius: 50%;
    background: linear-gradient(145deg, #FFD700, #FFC107);
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    font-weight: bold;
    border: 2px solid #B8860B;
    font-size: 1rem;
    box-shadow: 0 3px 6px rgba(0,0,0,0.1);
    transition: var(--transition);
  }
  
  .coin:hover {
    transform: translateY(-2px);
    box-shadow: 0 5px 10px rgba(0,0,0,0.15);
  }
  
  .coin:active {
    transform: translateY(1px);
  }
  
  .button-group {
    display: flex;
    gap: 15px;
    margin-top: 20px;
  }
  
  button {
    background-color: var(--primary-color);
    color: white;
    border: none;
    padding: 12px 20px;
    border-radius: var(--border-radius);
    cursor: pointer;
    font-weight: 600;
    font-size: 1rem;
    flex: 1;
    transition: var(--transition);
    box-shadow: 0 2px 5px rgba(0,0,0,0.1);
  }
  
  button:hover:not(:disabled) {
    background-color: var(--primary-dark);
    box-shadow: 0 4px 8px rgba(0,0,0,0.15);
  }
  
  button:disabled {
    background-color: #cccccc;
    cursor: not-allowed;
    opacity: 0.7;
  }
  
  .start-button {
    background-color: var(--success-color);
    padding: 15px 30px;
    font-size: 1.2rem;
    display: block;
    margin: 0 auto;
    width: 50%;
    min-width: 200px;
  }
  
  .start-button:hover {
    background-color: #2d9449;
  }
  
  .purchase-button {
    background-color: var(--success-color);
  }
  
  .purchase-button:hover:not(:disabled) {
    background-color: #2d9449;
  }
  
  .cancel-button {
    background-color: var(--danger-color);
  }
  
  .cancel-button:hover {
    background-color: #d32f2f;
  }
  
  .dispensed {
    border: 2px dashed #ccc;
    padding: 20px 15px;
    min-height: 80px;
    margin-top: 30px;
    border-radius: var(--border-radius);
    text-align: center;
    background-color: var(--neutral-color);
    position: relative;
  }
  
  .dispensed::before {
    content: "Nampan Pengambilan";
    position: absolute;
    top: -10px;
    left: 15px;
    background-color: white;
    padding: 0 10px;
    font-size: 0.85rem;
    color: var(--text-light);
  }
  
  .dispensed h3 {
    margin-top: 0;
  }
  
  .machine-state {
    margin-top: 30px;
    font-family: monospace;
    background-color: #f0f0f0;
    padding: 10px;
    border-radius: var(--border-radius);
    font-size: 0.9em;
    color: var(--text-light);
  }
  
  .visually-hidden {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border: 0;
  }
```
