### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by roberthenniger** [jsfiddle/jsfiddle-users#2036]
### Error code

ERRW:0.9:TTH0.9

### Were you logged in?

Yes

### Your username (if logged in)

roberthenniger

### Your HTML

```html
<div></div>
```

### Your JavaScript

```javascript

```

### Your CSS

```css
.parent {
display:none;
}
```
