### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by PatricEriksson** [jsfiddle/jsfiddle-users#2038]
### Error code

ERRW:1.0:K1.0

### Were you logged in?

Yes

### Your username (if logged in)

StepPatric

### Your HTML

```html
<link rel="stylesheet" href="https://use.typekit.net/qht6rho.css" />
<button class="original-button">
  <span class="btn-content">VISA ALLA PRODUKTER</span>
</button>
```

### Your JavaScript

```javascript
document.querySelectorAll(".original-button").forEach((btn) => {
  btn.addEventListener("click", function (e) {
    const circle = document.createElement("span");
    circle.classList.add("ripple");
    this.appendChild(circle);

    const d = Math.max(this.clientWidth, this.clientHeight);
    circle.style.width = circle.style.height = d + "px";
    const rect = this.getBoundingClientRect();
    circle.style.left = e.clientX - rect.left - d / 2 + "px";
    circle.style.top = e.clientY - rect.top - d / 2 + "px";

    circle.style.animation = "ripple 600ms linear";
    circle.addEventListener("animationend", () => circle.remove());
  });
});
```

### Your CSS

```css
.original-button {
  font-family: "avenir-lt-pro", sans-serif;
  font-weight: 100;
  position: relative;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
  border: none;
  border-radius: 2px;
  width: 200px;
  height: 40px;
  cursor: pointer;
  transform: scale(1);
  transition: transform 0.2s ease-in-out;
  color: #fff;
  box-shadow:
    0 1px 1px 0 rgba(0, 0, 0, 0.14),
    0 2px 1px -1px rgba(0, 0, 0, 0.12),
    0 1px 3px 0 rgba(0, 0, 0, 0.2);
}

.original-button::before {
  content: "";
  position: absolute;
  inset: 0;
  border-radius: inherit;
  background-image: linear-gradient(
    180deg,
    rgba(0, 53, 77, 1) 0%,
    rgba(33, 115, 143, 1) 33%,
    rgba(33, 115, 143, 1) 66%,
    rgba(0, 53, 77, 1) 100%
  );
  background-size: 100% 300%;
  background-position: center top;
  transform: scale(1);
  transition:
    background-position 0.2s ease-in-out,
    transform 0.2s ease-in-out;

  box-shadow:
    0 1px 1px 0 rgba(0, 0, 0, 0.14),
    0 2px 1px -1px rgba(0, 0, 0, 0.12),
    0 1px 3px 0 rgba(0, 0, 0, 0.2);
  z-index: -1;
}

.original-button:hover::before {
  background-position: center bottom;
}

.original-button:active::before {
  box-shadow:
    0 1px 1px 0 rgba(0, 0, 0, 0.1),
    0 1px 1px -1px rgba(0, 0, 0, 0.1),
    0 1px 2px 0 rgba(0, 0, 0, 0.14);
}

.original-button .ripple {
  position: absolute;
  border-radius: 50%;
  transform: scale(0);
  background-color: rgba(255, 255, 255, 0.4);
  pointer-events: none;
  will-change: transform, opacity;
}
@keyframes ripple {
  to {
    transform: scale(4);
    opacity: 0;
  }
}
```
