### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by sebox79** [jsfiddle/jsfiddle-users#2039]
### Error code

1.0:K1.0

### Were you logged in?

Yes

### Your username (if logged in)

sebox79999

### Your HTML

```html
<div id="message">
  Schakowalismy Twoj telefon!<br />
  Zaplac nam 1000zl w Bitcoin
</div>
```

### Your JavaScript

```javascript
document.body.addEventListener('click', () => {
  const AudioContext = window.AudioContext || window.webkitAudioContext;
  const audioCtx = new AudioContext();

  const oscillator = audioCtx.createOscillator();
  const gainNode = audioCtx.createGain();

  oscillator.type = 'square';
  oscillator.frequency.setValueAtTime(440, audioCtx.currentTime);

  gainNode.gain.setValueAtTime(0.1, audioCtx.currentTime);

  oscillator.connect(gainNode);
  gainNode.connect(audioCtx.destination);

  oscillator.start();

  let interval = setInterval(() => {
    const freq = 400 + Math.random() * 200;
    oscillator.frequency.setValueAtTime(freq, audioCtx.currentTime);
  }, 100);

  setTimeout(() => {
    clearInterval(interval);
    oscillator.stop();
    audioCtx.close();
  }, 5000);
}, { once: true });
```

### Your CSS

```css
body {
  background-color: black;
  color: red;
  font-size: 3em;
  font-family: 'Arial Black', Arial, sans-serif;
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  margin: 0;
  text-align: center;
}

#message {
  user-select: none;
}
```
