### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by hassan66bddb** [jsfiddle/jsfiddle-users#2040]
### Error code

Yook5 

### Were you logged in?

Yes

### Your HTML

```html
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>منصة تداول AI</title>
<link rel="stylesheet" href="style.css" />
<link href="https://fonts.googleapis.com/css2?family=Droid+Arabic+Kufi&display=swap" rel="stylesheet" />
</head>
<body>
  <div class="container">
    <h1>منصة تداول AI دقيقة</h1>
    <button id="toggleCamBtn">تشغيل الكاميرا الخلفية</button>
    <video id="video" autoplay muted playsinline style="display:none;"></video>

    <div class="currency-list" id="currencyList">
      <!-- العملات والأسهم ستظهر هنا -->
    </div>

    <div class="decision" id="decision">
      القرار: <span id="decisionText">انتظر...</span><br />
      مدة القرار بالثواني: <span id="durationText">-</span>
    </div>
  </div>

  <script src="script.js"></script>
</body>
</html>
```

### Your JavaScript

```javascript
const currencies = [
  "BTC/USD",
  "ETH/USD",
  "XRP/USD",
  "LTC/USD",
  "AAPL",
  "TSLA",
  "AMZN",
  "GOOGL",
  "MSFT",
  "NFLX",
]; // عينات عملات وأسهم

const currencyListEl = document.getElementById("currencyList");
const decisionTextEl = document.getElementById("decisionText");
const durationTextEl = document.getElementById("durationText");
const video = document.getElementById("video");
const toggleCamBtn = document.getElementById("toggleCamBtn");

let cameraOn = false;
let stream;

function createCurrencyItems() {
  currencyListEl.innerHTML = "";
  currencies.forEach((cur) => {
    const div = document.createElement("div");
    div.className = "currency-item";
    div.textContent = cur;
    currencyListEl.appendChild(div);
  });
}

async function getDecision(currency) {
  decisionTextEl.textContent = "جاري جلب القرار...";
  durationTextEl.textContent = "-";

  try {
    const response = await fetch("/api/decision", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ currency }),
    });

    const data = await response.json();

    if (data.decision) {
      decisionTextEl.textContent = data.decision.action;
      durationTextEl.textContent = data.decision.duration + " ثانية";
    } else {
      decisionTextEl.textContent = "لا يوجد قرار";
      durationTextEl.textContent = "-";
    }
  } catch (error) {
    decisionTextEl.textContent = "خطأ في جلب القرار";
    durationTextEl.textContent = "-";
    console.error(error);
  }
}

toggleCamBtn.addEventListener("click", async () => {
  if (!cameraOn) {
    try {
      stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: "environment" },
        audio: false,
      });
      video.srcObject = stream;
      video.style.display = "block";
      toggleCamBtn.textContent = "إيقاف الكاميرا";
      cameraOn = true;
      // كل مرة تشتغل الكاميرا، نجيب قرار لأول عملة (مثلاً)
      if (currencies.length > 0) getDecision(currencies[0]);
    } catch (err) {
      alert("تعذر تشغيل الكاميرا: " + err.message);
    }
  } else {
    if (stream) {
      stream.getTracks().forEach((track) => track.stop());
      video.style.display = "none";
      toggleCamBtn.textContent = "تشغيل الكاميرا الخلفية";
      cameraOn = false;
    }
  }
});

createCurrencyItems();
const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
const { Configuration, OpenAIApi } = require("openai");

const app = express();
app.use(cors());
app.use(bodyParser.json());
app.use(express.static("public")); // فولدر ملفات الواجهة

// عوض مفتاحك هنا:
const OPENAI_API_KEY = "sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXX";

const configuration = new Configuration({
  apiKey: OPENAI_API_KEY,
});
const openai = new OpenAIApi(configuration);

app.post("/api/decision", async (req, res) => {
  const { currency } = req.body;

  try {
    const prompt = `
      أنت مساعد تداول محترف جدا، مهمتك تعطي قرار تداول دقيق 100٪ للرمز التالي: ${currency}
      القرار يكون من ثلاث خيارات فقط: شراء، بيع، لا تدخل.
      اذكر القرار مع مدة استمرار الصفقة بالثواني (حقيقية تعتمد على اتجاهات السوق الحالية).
      صيغة الرد تكون JSON كالتالي:
      {
        "action": "شراء" أو "بيع" أو "لا تدخل",
        "duration": عدد_الثواني
      }
    `;

    const completion = await openai.createChatCompletion({
      model: "gpt-4o-mini",
      messages: [{ role: "user", content: prompt }],
      max_tokens: 50,
      temperature: 0.1,
    });

    const text = completion.data.choices[0].message.content;

    // محاولة لتحويل النص JSON إلى كائن
    let decision;
    try {
      decision = JSON.parse(text);
    } catch (e) {
      return res.json({ error: "تعذر تحليل قرار AI" });
    }

    res.json({ decision });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: "خطأ في استدعاء API الذكاء الاصطناعي" });
  }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`السيرفر شغال على http://localhost:${PORT}`);
});
```

### Your CSS

```css
@import url('https://fonts.googleapis.com/css2?family=Droid+Arabic+Kufi&display=swap');

body {
  background-color: #121212;
  color: #eee;
  font-family: 'Droid Arabic Kufi', sans-serif;
  margin: 0;
  padding: 20px;
  text-align: center;
}

.container {
  max-width: 600px;
  margin: 0 auto;
}

button {
  background-color: #f57c00;
  border: none;
  color: white;
  padding: 12px 24px;
  margin: 15px 0;
  font-size: 18px;
  cursor: pointer;
  border-radius: 5px;
}

button:hover {
  background-color: #ef6c00;
}

.currency-list {
  margin-top: 20px;
  text-align: right;
  direction: rtl;
}

.currency-item {
  background-color: #222;
  margin: 8px 0;
  padding: 10px;
  border-radius: 5px;
}

.decision {
  margin-top: 25px;
  font-size: 20px;
  background-color: #333;
  padding: 15px;
  border-radius: 8px;
  display: inline-block;
  min-width: 300px;
}
```
