### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by hassan66bddb** [jsfiddle/jsfiddle-users#2044]
### Error code

errw:1.0:K1.0:RC0.25

### Were you logged in?

Yes

### Your username (if logged in)

حسن مهاوي

### Your HTML

```html
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>منصة تداول AI</title>
<link rel="stylesheet" href="style.css" />
</head>
<body>

<h1>منصة تداول الذكاء الاصطناعي</h1>

<div class="camera-container">
  <video id="video" autoplay playsinline></video>
</div>

<div class="controls">
  <button id="startBtn">تشغيل الكاميرا الخلفية</button>
  <button id="stopBtn" disabled>إيقاف الكاميرا</button>
</div>

<select id="assetSelect" aria-label="اختيار العملات والأسهم">
  <option value="">اختر العملة أو السهم</option>
  <option value="BTCUSD">بيتكوين - BTC/USD</option>
  <option value="ETHUSD">إيثيريوم - ETH/USD</option>
  <option value="AAPL">آبل - AAPL</option>
  <option value="GOOGL">جوجل - GOOGL</option>
  <option value="EURUSD">اليورو مقابل الدولار - EUR/USD</option>
</select>

<input type="file" id="uploadImage" accept="image/*" aria-label="رفع صورة الشارت" />

<div class="decisions" id="decisionsContainer">
  <div class="decision-box" id="chatgptDecision">
    <h3>ChatGPT</h3>
    <p>القرار: -</p>
    <p>مدة الاستمرار: -</p>
  </div>
  <div class="decision-box" id="googleGeminiDecision">
    <h3>Google Gemini</h3>
    <p>القرار: -</p>
    <p>مدة الاستمرار: -</p>
  </div>
  <div class="decision-box" id="deepSeeDecision">
    <h3>DeepSee</h3>
    <p>القرار: -</p>
    <p>مدة الاستمرار: -</p>
  </div>
</div>

<div class="loading" id="loadingText"></div>

<script src="script.js"></script>
</body>
</html>
```

### Your JavaScript

```javascript
const video = document.getElementById("video");
const startBtn = document.getElementById("startBtn");
const stopBtn = document.getElementById("stopBtn");
const uploadImage = document.getElementById("uploadImage");
const loadingText = document.getElementById("loadingText");
const assetSelect = document.getElementById("assetSelect");

let stream;

startBtn.onclick = async () => {
  if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
    try {
      stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: { exact: "environment" } },
        audio: false
      });
      video.srcObject = stream;
      startBtn.disabled = true;
      stopBtn.disabled = false;
    } catch (err) {
      alert("خطأ في تشغيل الكاميرا الخلفية: " + err.message);
    }
  } else {
    alert("متصفحك لا يدعم الكاميرا.");
  }
};

stopBtn.onclick = () => {
  if (stream) {
    stream.getTracks().forEach(track => track.stop());
    video.srcObject = null;
    startBtn.disabled = false;
    stopBtn.disabled = true;
  }
};

// دالة محاكاة ارسال صورة وطلب القرار من API
async function requestDecision(apiName, imageData, asset) {
  loadingText.textContent = `جاري جلب القرار من ${apiName}...`;
  await new Promise(r => setTimeout(r, 2000)); // محاكاة تأخير
  const decisions = ["شراء", "بيع", "لا تدخل"];
  const decision = decisions[Math.floor(Math.random() * decisions.length)];
  const duration = Math.floor(Math.random() * 90) + 30;
  loadingText.textContent = "";
  return { decision, duration };
}

async function handleImageUpload(file) {
  if (!assetSelect.value) {
    alert("يرجى اختيار العملة أو السهم أولاً");
    return;
  }
  const reader = new FileReader();
  reader.onload = async function(event) {
    const imageData = event.target.result;
    const results = await Promise.all([
      requestDecision("ChatGPT", imageData, assetSelect.value),
      requestDecision("Google Gemini", imageData, assetSelect.value),
      requestDecision("DeepSee", imageData, assetSelect.value),
    ]);
    const [chatGPT, googleGemini, deepSee] = results;
    document.querySelector("#chatgptDecision p:nth-child(2)").textContent = `القرار: ${chatGPT.decision}`;
    document.querySelector("#chatgptDecision p:nth-child(3)").textContent = `مدة الاستمرار: ${chatGPT.duration} ثانية`;
    document.querySelector("#googleGeminiDecision p:nth-child(2)").textContent = `القرار: ${googleGemini.decision}`;
    document.querySelector("#googleGeminiDecision p:nth-child(3)").textContent = `مدة الاستمرار: ${googleGemini.duration} ثانية`;
    document.querySelector("#deepSeeDecision p:nth-child(2)").textContent = `القرار: ${deepSee.decision}`;
    document.querySelector("#deepSeeDecision p:nth-child(3)").textContent = `مدة الاستمرار: ${deepSee.duration} ثانية`;
  };
  reader.readAsDataURL(file);
}

uploadImage.onchange = (e) => {
  const file = e.target.files[0];
  if (file) {
    handleImageUpload(file);
  }
};
```

### Your CSS

```css
body {
  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
  background: #111;
  color: #eee;
  margin: 0; padding: 20px;
}
h1 {
  text-align:center;
  margin-bottom: 20px;
}
.camera-container {
  position: relative;
  width: 100%;
  max-width: 600px;
  margin: 0 auto 20px auto;
  border: 5px solid red;
  border-radius: 10px;
  overflow: hidden;
}
video {
  width: 100%;
  height: auto;
  background: black;
}
.controls {
  text-align: center;
  margin: 10px 0;
}
button {
  font-size: 18px;
  padding: 10px 20px;
  margin: 5px;
  cursor: pointer;
  border-radius: 6px;
  border: none;
  background: #d33;
  color: white;
  transition: background 0.3s ease;
}
button:hover {
  background: #b00;
}
select, input[type=file] {
  font-size: 16px;
  padding: 8px;
  margin: 10px auto;
  display: block;
  max-width: 300px;
  width: 90%;
  border-radius: 5px;
  border: none;
}
.decisions {
  max-width: 600px;
  margin: 20px auto;
  background: #222;
  padding: 15px;
  border-radius: 10px;
}
.decision-box {
  background: #333;
  padding: 10px;
  margin-bottom: 10px;
  border-radius: 8px;
}
.decision-box h3 {
  margin: 0 0 5px 0;
}
.loading {
  text-align: center;
  font-size: 16px;
  margin-top: 10px;
}
```
