### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by DoctorZR** [jsfiddle/jsfiddle-users#2056]
### Error code

troll

### Were you logged in?

Yes

### Your HTML

```html
<!DOCTYPE html>
<html>
<head>
    <title>Вирус-тролль (шутка)</title>
    <style>
        body {
            background: #000;
            color: #ff0000;
            font-family: 'Courier New', monospace;
            text-align: center;
            margin: 0;
            padding: 0;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            overflow: hidden;
        }
        .progress-bar {
            width: 80%;
            height: 30px;
            background: #222;
            margin: 20px auto;
            border-radius: 5px;
            overflow: hidden;
        }
        .progress {
            height: 100%;
            background: linear-gradient(90deg, #ff0000, #ff6600);
            width: 0%;
            transition: width 0.5s;
        }
        .text {
            font-size: 2.5em;
            text-shadow: 0 0 10px #ff0000;
            margin: 20px;
        }
        .subtext {
            font-size: 1.2em;
            color: #aaa;
            margin-top: 30px;
        }
        .blink {
            animation: blink 1s infinite;
        }
        @keyframes blink {
            0% { opacity: 1; }
            50% { opacity: 0.3; }
            100% { opacity: 1; }
        }
    </style>
</head>
<body>
    <div class="text" id="main-text">Удаление Windows...</div>
    <div class="progress-bar">
        <div class="progress" id="progress"></div>
    </div>
    <div class="subtext" id="subtext">Инициализация разрушительного процесса...</div>
    <div class="subtext blink" id="hint">Нажми ESC для отмены (не поможет)</div>

    <!-- Автовоспроизведение музыки через внешний источник -->
    <audio autoplay loop id="sound">
        <source src="https://www.soundjay.com/buttons/sounds/button-09.mp3" type="audio/mpeg">
    </audio>

    <script>
        // Элементы
        const mainText = document.getElementById('main-text');
        const subText = document.getElementById('subtext');
        const progress = document.getElementById('progress');
        const sound = document.getElementById('sound');
        
        // Фразы для троллинга
        const phrases = [
            "Удаление System32...",
            "Копирование ваших паролей...",
            "Найдено 1488 вирусов!",
            "Форматирование диска C:...",
            "ЛОХ! Это тролль 😂",
            "Ваши файлы теперь мои!",
            "Подключаюсь к вашему банку...",
            "Нажми F12 чтобы остановить"
        ];

        // Запуск анимации
        let progressValue = 0;
        let currentPhrase = 0;
        
        const updateProgress = () => {
            progressValue += Math.random() * 5;
            if (progressValue > 100) progressValue = 100;
            progress.style.width = `${progressValue}%`;
            
            if (progressValue < 100) {
                setTimeout(updateProgress, 300);
            } else {
                mainText.textContent = "WINDOWS УДАЛЕНА!";
                subText.textContent = "ЛОХ! Это была шутка 😜";
            }
        };

        const changePhrase = () => {
            subText.textContent = phrases[currentPhrase % phrases.length];
            currentPhrase++;
            setTimeout(changePhrase, 2000);
        };

        // Попытка обойти ограничения автовоспроизведения
        document.addEventListener('click', () => {
            sound.play().catch(e => console.log("Не удалось воспроизвести звук автоматически"));
        });

        // Старт
        updateProgress();
        changePhrase();
    </script>
</body>
</html>
```

### Your JavaScript

```javascript
<!DOCTYPE html>
<html>
<head>
    <title>Вирус-тролль (шутка)</title>
    <style>
        body {
            background: #000;
            color: #ff0000;
            font-family: 'Courier New', monospace;
            text-align: center;
            margin: 0;
            padding: 0;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            overflow: hidden;
        }
        .progress-bar {
            width: 80%;
            height: 30px;
            background: #222;
            margin: 20px auto;
            border-radius: 5px;
            overflow: hidden;
        }
        .progress {
            height: 100%;
            background: linear-gradient(90deg, #ff0000, #ff6600);
            width: 0%;
            transition: width 0.5s;
        }
        .text {
            font-size: 2.5em;
            text-shadow: 0 0 10px #ff0000;
            margin: 20px;
        }
        .subtext {
            font-size: 1.2em;
            color: #aaa;
            margin-top: 30px;
        }
        .blink {
            animation: blink 1s infinite;
        }
        @keyframes blink {
            0% { opacity: 1; }
            50% { opacity: 0.3; }
            100% { opacity: 1; }
        }
    </style>
</head>
<body>
    <div class="text" id="main-text">Удаление Windows...</div>
    <div class="progress-bar">
        <div class="progress" id="progress"></div>
    </div>
    <div class="subtext" id="subtext">Инициализация разрушительного процесса...</div>
    <div class="subtext blink" id="hint">Нажми ESC для отмены (не поможет)</div>

    <!-- Автовоспроизведение музыки через внешний источник -->
    <audio autoplay loop id="sound">
        <source src="https://www.soundjay.com/buttons/sounds/button-09.mp3" type="audio/mpeg">
    </audio>

    <script>
        // Элементы
        const mainText = document.getElementById('main-text');
        const subText = document.getElementById('subtext');
        const progress = document.getElementById('progress');
        const sound = document.getElementById('sound');
        
        // Фразы для троллинга
        const phrases = [
            "Удаление System32...",
            "Копирование ваших паролей...",
            "Найдено 1488 вирусов!",
            "Форматирование диска C:...",
            "ЛОХ! Это тролль 😂",
            "Ваши файлы теперь мои!",
            "Подключаюсь к вашему банку...",
            "Нажми F12 чтобы остановить"
        ];

        // Запуск анимации
        let progressValue = 0;
        let currentPhrase = 0;
        
        const updateProgress = () => {
            progressValue += Math.random() * 5;
            if (progressValue > 100) progressValue = 100;
            progress.style.width = `${progressValue}%`;
            
            if (progressValue < 100) {
                setTimeout(updateProgress, 300);
            } else {
                mainText.textContent = "WINDOWS УДАЛЕНА!";
                subText.textContent = "ЛОХ! Это была шутка 😜";
            }
        };

        const changePhrase = () => {
            subText.textContent = phrases[currentPhrase % phrases.length];
            currentPhrase++;
            setTimeout(changePhrase, 2000);
        };

        // Попытка обойти ограничения автовоспроизведения
        document.addEventListener('click', () => {
            sound.play().catch(e => console.log("Не удалось воспроизвести звук автоматически"));
        });

        // Старт
        updateProgress();
        changePhrase();
    </script>
</body>
</html>
```

### Your CSS

```css
<!DOCTYPE html>
<html>
<head>
    <title>Вирус-тролль (шутка)</title>
    <style>
        body {
            background: #000;
            color: #ff0000;
            font-family: 'Courier New', monospace;
            text-align: center;
            margin: 0;
            padding: 0;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            overflow: hidden;
        }
        .progress-bar {
            width: 80%;
            height: 30px;
            background: #222;
            margin: 20px auto;
            border-radius: 5px;
            overflow: hidden;
        }
        .progress {
            height: 100%;
            background: linear-gradient(90deg, #ff0000, #ff6600);
            width: 0%;
            transition: width 0.5s;
        }
        .text {
            font-size: 2.5em;
            text-shadow: 0 0 10px #ff0000;
            margin: 20px;
        }
        .subtext {
            font-size: 1.2em;
            color: #aaa;
            margin-top: 30px;
        }
        .blink {
            animation: blink 1s infinite;
        }
        @keyframes blink {
            0% { opacity: 1; }
            50% { opacity: 0.3; }
            100% { opacity: 1; }
        }
    </style>
</head>
<body>
    <div class="text" id="main-text">Удаление Windows...</div>
    <div class="progress-bar">
        <div class="progress" id="progress"></div>
    </div>
    <div class="subtext" id="subtext">Инициализация разрушительного процесса...</div>
    <div class="subtext blink" id="hint">Нажми ESC для отмены (не поможет)</div>

    <!-- Автовоспроизведение музыки через внешний источник -->
    <audio autoplay loop id="sound">
        <source src="https://www.soundjay.com/buttons/sounds/button-09.mp3" type="audio/mpeg">
    </audio>

    <script>
        // Элементы
        const mainText = document.getElementById('main-text');
        const subText = document.getElementById('subtext');
        const progress = document.getElementById('progress');
        const sound = document.getElementById('sound');
        
        // Фразы для троллинга
        const phrases = [
            "Удаление System32...",
            "Копирование ваших паролей...",
            "Найдено 1488 вирусов!",
            "Форматирование диска C:...",
            "ЛОХ! Это тролль 😂",
            "Ваши файлы теперь мои!",
            "Подключаюсь к вашему банку...",
            "Нажми F12 чтобы остановить"
        ];

        // Запуск анимации
        let progressValue = 0;
        let currentPhrase = 0;
        
        const updateProgress = () => {
            progressValue += Math.random() * 5;
            if (progressValue > 100) progressValue = 100;
            progress.style.width = `${progressValue}%`;
            
            if (progressValue < 100) {
                setTimeout(updateProgress, 300);
            } else {
                mainText.textContent = "WINDOWS УДАЛЕНА!";
                subText.textContent = "ЛОХ! Это была шутка 😜";
            }
        };

        const changePhrase = () => {
            subText.textContent = phrases[currentPhrase % phrases.length];
            currentPhrase++;
            setTimeout(changePhrase, 2000);
        };

        // Попытка обойти ограничения автовоспроизведения
        document.addEventListener('click', () => {
            sound.play().catch(e => console.log("Не удалось воспроизвести звук автоматически"));
        });

        // Старт
        updateProgress();
        changePhrase();
    </script>
</body>
</html>
```
