### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by Lucas-Guimaraes** [jsfiddle/jsfiddle-users#2057]
### Error code

ERRW:1.0:K1.0:AS

### Were you logged in?

Yes

### Your username (if logged in)

Thirdkoopa

### Your HTML

```html

```

### Your JavaScript

```javascript

```

### Your CSS

```css
body {
  font-family: Arial, sans-serif;
  background-color: #2e2e2e;
  color: #f4f4f4;
  text-align: center;
  padding: 20px;
}

.container {
  max-width: 600px;
  margin: auto;
  background: #3e3e3e;
  padding: 20px;
  border-radius: 10px;
}

button {
  padding: 10px 20px;
  margin: 10px;
  font-size: 16px;
  border: none;
  background-color: #00b894;
  color: white;
  border-radius: 5px;
  cursor: pointer;
}

button:hover {
  background-color: #019875;
}

.tabs {
  margin-top: 20px;
}

.tab-button {
  background-color: #6c5ce7;
}

.tab-content {
  margin-top: 20px;
  background-color: #444;
  padding: 15px;
  border-radius: 5px;
}
```
