### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by koabehr** [jsfiddle/jsfiddle-users#2058]
### Error code

ERRW:1.0:K1.0:AS

### Were you logged in?

Yes

### Your username (if logged in)

koabehr

### Your HTML

```html
<div id="customAccessPermitInnerBox" class="custom-access-permit-inner-box">
  <a href="https://imgbb.com/"><img src="https://i.ibb.co/xSP5qYtj/Access-Permit-Inner.png" alt="Access-Permit-Inner" border="0"></a>
  <div class="api-btn api-btn-accesspermit static-label">Access Permit</div>
  <button class="api-btn api-btn-name" type="button">NAME</button>
  <button class="api-btn api-btn-nationality" type="button">NATIONALITY</button>
  <button class="api-btn api-btn-purpose" type="button">PURPOSE</button>
  <button class="api-btn api-btn-height" type="button">HEIGHT</button>
  <button class="api-btn api-btn-appearance" type="button">PHYSICAL APPEARANCE</button>
  <button class="api-btn api-btn-id" type="button">ID NUMBER</button>
  <button class="api-btn api-btn-duration" type="button">DURATION</button>
  <button class="api-btn api-btn-weight" type="button">WEIGHT</button>
  <button class="api-btn api-btn-enterby" type="button">ENTER BY</button>
</div>
```

### Your JavaScript

```javascript
document.querySelectorAll('.api-btn:not(.static-label)').forEach(btn => {
  btn.addEventListener('click', function () {
    btn.classList.toggle('active');
  });
});
```

### Your CSS

```css
@import url('https://fonts.googleapis.com/css2?family=VT323&display=swap');

body {
background: #222;
font-family: 'VT323', monospace;
}

.custom-access-permit-inner-box {
position: relative;
width: 400px;
height: 270px;
margin: 40px auto;
background: none;
box-shadow: none;
border: none;
padding: 0;
}

.api-bg {
position: absolute;
top: 0; left: 0;
width: 400px;
height: 270px;
object-fit: none;
display: block;
border-radius: 8px;
pointer-events: none;
user-select: none;
z-index: 1;
}

.api-btn {
position: absolute;
background: rgba(0,0,0,0.0);
color: #776789;
font-family: 'VT323', monospace;
font-size: 1.3em;
border: none;
outline: none;
cursor: pointer;
padding: 0;
margin: 0;
transition: color 0.2s, background 0.2s;
border-radius: 4px;
min-width: 0;
min-height: 0;
user-select: none;
z-index: 2;
text-align: center
}

.api-btn.active {
background: #2cbc63;
color: #fff;
}

.api-btn-accesspermit.static-label {
  font-size: 2.5em;
}

.api-btn-accesspermit { top: 20px;  left: 45px;  width: auto; }
.api-btn-name         { top: 105px; left: 132px; width: auto; }
.api-btn-nationality  { top: 150px; left: 31px;  width: auto; }
.api-btn-purpose      { top: 194px; left: 31px;  width: auto; }
.api-btn-height       { top: 238px; left: 31px;  width: auto; }
.api-btn-appearance   { top: 282px; left: 31px;  width: auto; }
.api-btn-id           { top: 150px; left: 156px; width: auto; }
.api-btn-duration     { top: 194px; left: 156px; width: auto; }
.api-btn-weight       { top: 238px; left: 156px; width: auto; }
.api-btn-enterby      { top: 326px; left: 156px; width: auto; }
```
