### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by CPZ0721** [jsfiddle/jsfiddle-users#2062]
### Error code

ERRW:1.0:K1.0:PRMS0.5:AS

### Were you logged in?

Yes

### Your HTML

```html
<h1>⚖️ 法條判官 AI 小遊戲</h1>

<label for="levelSelect">選擇難度：</label>
<select id="levelSelect" onchange="startLevel(this.value)">
  <option value="beginner">初階</option>
  <option value="intermediate">進階</option>
  <option value="expert">專家</option>
</select>

<h2 id="question">載入中...</h2>
<div id="options"></div>
<div id="feedback" style="margin-top: 20px;"></div>
<p id="scoreDisplay">目前得分：0 分</p>
```

### Your JavaScript

```javascript
const questions = {
  beginner: [
    {
      question: "你在網路上匿名張貼「某同學偷錢」，但沒有證據。可能會觸犯？",
      options: ["誹謗罪", "公然侮辱罪", "妨害秘密罪", "無罪，因為匿名不算"],
      answer: 0,
      explanation: "即使匿名也可能構成誹謗，因為仍會造成名譽受損。",
    },
    {
      question: "你偷拍老師上課打瞌睡，傳到 IG，會有什麼法律風險？",
      options: ["妨害名譽", "妨害秘密", "智慧財產權", "沒有違法"],
      answer: 1,
      explanation: "未經同意偷拍屬於妨害秘密，尤其在非公開場合。",
    },
    {
      question: "餐廳外標示「本店拒絕服務同性情侶」，此行為違反？",
      options: [
        "性別平等教育法",
        "民法",
        "性別工作平等法",
        "性別平等法（性別平權法）",
      ],
      answer: 3,
      explanation: "此為歧視性行為，違反性別平等相關法律。",
    },
    {
      question: "在學校走廊張貼『某老師教很爛』的大字報，會違法嗎？",
      options: [
        "不會，言論自由",
        "可能涉及誹謗",
        "構成毀損罪",
        "是學術評論自由",
      ],
      answer: 1,
      explanation: "張貼不實或傷害名譽文字，可能觸犯誹謗。",
    },
    {
      question: "你幫朋友在 FB 出售盜版漫畫，會觸犯？",
      options: ["誹謗罪", "竊盜罪", "著作權法", "公然侮辱罪"],
      answer: 2,
      explanation: "盜版內容買賣涉及著作權侵害。",
    },
    {
      question: "你在公共場合大聲播放別人音樂，可能觸犯？",
      options: ["噪音管制法", "著作權法", "刑法妨害安寧罪", "無罪"],
      answer: 2,
      explanation: "擾亂公共安寧可能觸犯妨害安寧罪。",
    },
    {
      question: "網路發表不實資訊誹謗他人，可能觸犯？",
      options: ["誹謗罪", "妨害秘密罪", "恐嚇罪", "無罪"],
      answer: 0,
      explanation: "散布不實言論傷害名譽，可能構成誹謗罪。",
    },
    {
      question: "你未經同意使用他人照片當社群大頭貼，可能違反？",
      options: ["著作權法", "人格權", "隱私權", "公然侮辱罪"],
      answer: 1,
      explanation: "未經同意使用照片，侵犯他人人格權。",
    },
    {
      question: "校園內張貼廣告不經批准，可能違反？",
      options: ["校園管理規定", "著作權法", "妨害秘密罪", "民法"],
      answer: 0,
      explanation: "張貼廣告須經校園管理單位批准。",
    },
    {
      question: "使用他人帳號登入網路服務，可能觸犯？",
      options: ["妨害秘密罪", "竊盜罪", "詐欺罪", "妨害電腦使用罪"],
      answer: 3,
      explanation: "未經許可使用他人帳號，可能違反妨害電腦使用罪。",
    },
  ],
  intermediate: [
    {
      question: "你在新聞留言區發表「政治人物X應該去死」，最可能構成？",
      options: ["言論自由範圍內", "恐嚇危害安全罪", "公然侮辱罪", "誹謗罪"],
      answer: 1,
      explanation: "涉及人身威脅，可能構成恐嚇危害安全罪。",
    },
    {
      question: "你拍下警察執勤過程並上傳網路，但未加馬賽克，最有可能發生？",
      options: [
        "違反刑法妨礙公務",
        "違反警察法",
        "無違法，符合新聞自由",
        "涉嫌妨害秘密",
      ],
      answer: 2,
      explanation: "在公共場所錄影通常屬新聞自由範圍。",
    },
    {
      question: "你將購買的正版音樂轉傳給朋友，是否違法？",
      options: [
        "沒關係，已付費",
        "違反智慧財產權法的重製權",
        "構成刑法竊盜罪",
        "屬於朋友間分享，合理使用",
      ],
      answer: 1,
      explanation: "未經授權重製與散布，屬於侵權行為。",
    },
    {
      question: "你網拍標示『保證正品』但其實是山寨品，可能觸犯？",
      options: ["詐欺罪", "偽造文書", "民法侵權", "公平交易法"],
      answer: 0,
      explanation: "蓄意誤導消費者獲利，構成詐欺。",
    },
    {
      question: "老師上課放一整部電影給班級看，是否合理？",
      options: ["合理使用", "不合理使用", "違反學生權益", "構成營利行為"],
      answer: 1,
      explanation: "播放整部電影不符合理使用原則。",
    },
    {
      question:
        "同性婚姻在台灣已合法，若同志配偶其中一方住院，另一方能否以配偶身份簽署手術同意書？",
      options: [
        "不能，因醫院有權拒絕",
        "可以，已具法律上配偶身分",
        "不行，必須血親才可簽",
        "可簽署但無法律效力",
      ],
      answer: 1,
      explanation: "同性婚姻具法律效力，伴侶可行使醫療決策權。",
    },
    {
      question:
        "你用 ChatGPT 生成一整篇期末報告並未註明 AI 協助，老師指你違反學術誠信，可能原因為？",
      options: [
        "AI 不具智慧，無須註明",
        "老師不懂新科技",
        "未標明出處與協助方式，屬抄襲或代筆",
        "AI 是公共資源，不涉及誠信問題",
      ],
      answer: 2,
      explanation: "未註明生成來源屬於違反學術誠信，視同抄襲或代寫。",
    },
    {
      question:
        "你將同學設計的簡報內容上傳到自己的 IG 公開展示，卻未經對方同意，可能涉及？",
      options: ["合理使用", "著作權法侵害", "公然侮辱", "個資法問題"],
      answer: 1,
      explanation: "創作作品具著作權，需尊重原作者授權。",
    },
    {
      question:
        "某平台販售你的自拍照生成的 Deepfake 影片，你可依據哪部法律主張權益？",
      options: [
        "性騷擾防治法",
        "個人資料保護法與刑法妨害名譽",
        "無法可管",
        "商標法",
      ],
      answer: 1,
      explanation: "Deepfake 涉個資與名譽損害，得依個資法與刑法主張。",
    },
    {
      question:
        "你在 Dcard 上留言批評教授『常遲到，根本不備課』，結果被提告誹謗，哪種說法成立？",
      options: [
        "言論自由可無限制批評",
        "只要說實話就沒問題",
        "即便為真實亦應注意是否涉及誹謗",
        "只要匿名就無法追究",
      ],
      answer: 2,
      explanation: "即便為事實，若足以損害他人名譽，也可能構成誹謗。",
    },
  ],
  expert: [
    {
      question: "市府強制徵收土地蓋大型開發案，未通知居民，違反？",
      options: ["土地法", "行政程序法的聽證原則", "憲法第15條", "區域計畫法"],
      answer: 1,
      explanation: "行政程序法要求重大處分應給予當事人陳述意見機會。",
    },
    {
      question: "你模仿某族群口音直播獲利萬餘元，被檢舉，最可能違反？",
      options: [
        "公然侮辱罪",
        "就業服務法",
        "國家語言發展法",
        "刑法第305條恐嚇罪",
      ],
      answer: 0,
      explanation: "以歧視方式模仿族群言語可能構成公然侮辱。",
    },
    {
      question: "網紅推銷減肥產品，未標明「業配」，可能違反？",
      options: ["藥事法", "公平交易法", "電信法", "誹謗罪"],
      answer: 1,
      explanation: "未揭露廣告屬不實商業行為，違反公平交易法。",
    },
    {
      question: "你設計一個 AI 模型預測學生成績，未告知資料來源，違反？",
      options: ["憲法", "行政程序法", "個人資料保護法", "著作權法"],
      answer: 2,
      explanation: "蒐集個資用於分析必須明確揭露目的與處理方式。",
    },
    {
      question:
        "父親過世留下債務，你尚未辦理繼承登記也未聲請拋棄繼承，債權人來催討，法律上你會？",
      options: [
        "不須理會，尚未繼承",
        "可能要負清償責任",
        "可主張債務已清償",
        "以遺囑免除責任",
      ],
      answer: 1,
      explanation: "未在法定期間內聲請拋棄繼承，視為已承繼，須負債務清償責任。",
    },
    {
      question: "病人手術後出現併發症，認為醫院處置不當，應先採取？",
      options: [
        "直接提出刑事告訴",
        "申訴至健保署",
        "申請醫療鑑定",
        "向媒體投訴",
      ],
      answer: 2,
      explanation: "醫療爭議應先透過醫療鑑定判斷醫療行為有無過失。",
    },
    {
      question: "在未保險的情況下駕車撞人，對方受重傷，可能涉及？",
      options: [
        "僅民事賠償",
        "刑法過失傷害罪",
        "道路交通管理處罰條例",
        "無責任，因無保險",
      ],
      answer: 1,
      explanation: "駕駛肇事造成他人傷害，除民事責任，也可能觸犯刑法。",
    },
    {
      question: "一方長期失聯超過 7 年，配偶欲解除婚姻關係，法律上可透過？",
      options: [
        "民法訴請失蹤宣告",
        "強制離婚",
        "聲請撤銷結婚登記",
        "通知戶政機關",
      ],
      answer: 0,
      explanation: "依民法可聲請法院為失蹤人宣告，達成離婚效果。",
    },
    {
      question: "夫妻離婚後，未成年子女監護歸父方，母方仍可？",
      options: [
        "無任何探視權",
        "要求再分配財產",
        "請求改判監護",
        "繼續行使部分親權",
      ],
      answer: 3,
      explanation: "非監護方仍有親權與探視權，保障親子關係。",
    },
    {
      question: "遺囑中將所有財產遺贈他人，卻未留給直系親屬，這份遺囑？",
      options: ["完全有效", "將被全部撤銷", "仍須保留特留分", "法院可否決"],
      answer: 2,
      explanation: "依法直系血親享有最低遺產保障（特留分），不能被完全剝奪。",
    },
  ],
}

let score = 0 
let currentLevel = "beginner" 
let questionIndex = 0 
let levelQuestions = [] 
 
function startLevel(level) { 
  score = 0 
  questionIndex = 0 
  currentLevel = level 
  levelQuestions = [...questions[level]] 
  shuffle(levelQuestions) 
  showQuestion() 
  updateScore() 
} 
 
function showQuestion() { 
  if (questionIndex >= levelQuestions.length) { 
    document.getElementById("question").textContent = "🎉 恭喜完成所有題目！" 
    document.getElementById("options").innerHTML = "" 
    document.getElementById("feedback").innerHTML = `<p>總得分：${score} 分</p>` 
    return 
    document.getElementById("question").textContent = 
      `第 ${questionIndex + 1} 題／共 ${levelQuestions.length} 題\n${q.question}` 
  } 
 
  const q = levelQuestions[questionIndex] 
  document.getElementById("question").textContent = q.question 
  const optionsDiv = document.getElementById("options") 
  optionsDiv.innerHTML = "" 
  document.getElementById("feedback").innerHTML = "" 
 
  q.options.forEach((opt, i) => { 
    const btn = document.createElement("button") 
    btn.textContent = opt 
    btn.className = "option-btn" 
    btn.onclick = () => { 
  const isCorrect = i === q.answer; 
  if (isCorrect) score += 10; 
  updateScore(); 
 
  // ➤ 禁用所有選項按鈕 
  const allButtons = document.querySelectorAll('.option-btn'); 
  allButtons.forEach(button => button.disabled = true); 
 
  document.getElementById("feedback").innerHTML = `
  <p style="font-weight: bold; color: ${isCorrect ? 'green' : 'red'};">
    ${isCorrect ? '✅ 答對了！' : '❌ 答錯了！'}
  </p>
  <p><strong>解析：</strong>${q.explanation}</p>
  <button onclick="nextQuestion()">下一題 ▶</button>
`; 
}; 
    optionsDiv.appendChild(btn) 
  }) 
} 
 
function nextQuestion() { 
  questionIndex++ 
  showQuestion() 
} 
 
function updateScore() { 
  document.getElementById("scoreDisplay").textContent = `目前得分：${score} 分` 
} 
 
function shuffle(array) { 
  for (let i = array.length - 1; i > 0; i--) { 
    const j = Math.floor(Math.random() * (i + 1)) 
    ;[array[i], array[j]] = [array[j], array[i]] 
  } 
} 
 
window.onload = () => { 
  startLevel("beginner") 
}
```

### Your CSS

```css
body { 
  background-image: url('https://sdmntprwestus.oaiusercontent.com/files/00000000-ca7c-6230-a48d-1a804cac300e/raw?se=2025-06-03T12%3A18%3A04Z&sp=r&sv=2024-08-04&sr=b&scid=470ee5a2-d24f-5c27-ab3f-11fe3a561a35&skoid=add8ee7d-5fc7-451e-b06e-a82b2276cf62&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-06-03T07%3A56%3A51Z&ske=2025-06-04T07%3A56%3A51Z&sks=b&skv=2024-08-04&sig=z6yMBGZ3MW95fx%2Bs5hTW4dp557d/qEcq1cq4y8JGQf4%3D'); 
   background-size: cover; 
  background-position: center; 
  background-repeat: no-repeat; 
  background-attachment: fixed; 
  margin: 0; 
  padding: 0; 
} 
 
#question { 
  font-size: 20px; 
  margin-bottom: 20px; 
} 
 
.option-btn { 
display: block; 
margin: 10px auto; 
padding: 10px 20px; 
background-color: #007bff; 
color: white; 
border: none; 
border-radius: 6px; 
cursor: pointer; 
width: 80%; 
max-width: 300px; 
} 
.option-btn:hover { 
background-color: #0056b3; 
} 
select { 
font-size: 16px; 
margin-bottom: 20px; 
padding: 5px 10px; 
}
```
