### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by mike123456-ux** [jsfiddle/jsfiddle-users#2068]
### Error code

jiouhu123456

### Were you logged in?

Yes

### Your username (if logged in)

mike123456-ux

### Your HTML

```html
<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>彰化美食守護者</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="game-container">
        <div id="start-screen" class="game-section screen-background hidden">
            <h1>彰化美食守護者</h1>
            <button id="start-button" class="shine-button">開始遊戲</button>
        </div>

        <div id="main-menu" class="game-section screen-background hidden">
            <h2>彰化美食地圖</h2>
            <div id="foods-display"></div>
            <button id="level1-button" class="level-select-button shine-button">鳳眼糕記憶配對</button>
            <button id="level2-button" class="level-select-button shine-button">肉圓問答挑戰</button>
            <button id="level3-button" class="level-select-button shine-button">爌肉飯食材收集</button>
            <button id="level4-button" class="level-select-button shine-button">卦山燒迷宮</button>
            <button id="level5-button" class="level-select-button shine-button">蚵仔煎挑戰</button>
        </div>

        <div id="level1" class="level-section level-background hidden">
            <h3>鳳眼糕記憶配對</h3>
            <p>點擊翻開卡片，找出相同的鳳眼糕！</p>
            <div id="memory-game-board" class="memory-board"></div>
            <div id="level1-message" class="message-box hidden"></div>
            <button id="restart-level1" class="hidden shine-button">重新開始</button>
            <button id="next-level1" class="hidden shine-button">進入主選單</button>
        </div>

        <div id="level2" class="level-section level-background hidden">
            <h3>肉圓問答挑戰</h3>
            <p>選擇正確答案，守護美味肉圓！</p>
            <div id="question-box">
                <p id="question-text"></p>
                <div id="answers-container"></div>
            </div>
            <div id="level2-message" class="message-box hidden"></div>
            <button id="restart-level2" class="hidden shine-button">重新開始</button>
            <button id="next-level2" class="hidden shine-button">進入主選單</button>
        </div>

        <div id="level3" class="level-section level-background hidden">
            <h3>爌肉飯食材收集</h3>
            <p>點擊掉落的食材，收集製作爌肉飯所需材料！</p>
            <div id="collect-game-area"></div>
            <div id="score-display">分數: <span id="current-score">0</span> / <span id="target-score">10</span></div>
            <div id="level3-message" class="message-box hidden"></div>
            <button id="restart-level3" class="hidden shine-button">重新開始</button>
            <button id="next-level3" class="hidden shine-button">進入主選單</button>
        </div>

        <div id="level4" class="level-section level-background hidden">
            <h3>卦山燒迷宮</h3>
            <p>控制小點心通過迷宮，收集所有卦山燒！</p>
            <div id="maze-container">
                <canvas id="maze-canvas"></canvas>
            </div>
            <div id="level4-message" class="message-box hidden"></div>
            <button id="restart-level4" class="hidden shine-button">重新開始</button>
            <button id="next-level4" class="hidden shine-button">進入主選單</button>
        </div>

        <div id="level5" class="level-section level-background hidden">
            <h3>蚵仔煎挑戰</h3>
            <p>點擊正確的蚵仔煎，在時間內完成挑戰！</p>
            <div id="oyster-game-area"></div>
            <div id="oyster-score-time">分數: <span id="oyster-current-score">0</span> | 時間: <span id="oyster-time">30</span>s</div>
            <div id="level5-message" class="message-box hidden"></div>
            <button id="restart-level5" class="hidden shine-button">重新開始</button>
            <button id="next-level5" class="hidden shine-button">進入主選單</button>
        </div>

        <div id="final-dish-display" class="game-section screen-background hidden">
            <h2>恭喜您，已收集所有彰化美食！</h2>
            <div id="collected-foods-final"></div>
            <button id="return-to-start" class="shine-button">返回開始</button>
        </div>
    </div>
    <script src="script.js"></script>
</body>
</html>
```

### Your JavaScript

```javascript
const collectedFoods = {};
const foodNames = ["鳳眼糕", "肉圓", "爌肉飯", "卦山燒", "蚵仔煎"];
const foodImages = {
    "鳳眼糕": "https://imgur.com/fengyantagao.png",
    "肉圓": "https://imgur.com/rouyuan.png",
    "爌肉飯": "https://imgur.com/kuangroufan.png",
    "卦山燒": "https://imgur.com/guashanshao.png",
    "蚵仔煎": "https://imgur.com/kezaijian.png"
};

const screens = ["start-screen", "main-menu", "level1", "level2", "level3", "level4", "level5", "final-dish-display"];

const showScreen = (id) => {
    screens.forEach(screenId => document.getElementById(screenId)?.classList.add("hidden"));
    document.getElementById(id)?.classList.remove("hidden");
};

const updateCollectedFoodsDisplay = () => {
    const displayDiv = document.getElementById("foods-display");
    const finalDisplayDiv = document.getElementById("collected-foods-final");
    if (!displayDiv || !finalDisplayDiv) return;

    displayDiv.innerHTML = '';
    finalDisplayDiv.innerHTML = '';

    foodNames.forEach(food => {
        const item = document.createElement("div");
        item.className = "collected-food-item";
        item.style.backgroundImage = `url(${foodImages[food]})`;
        if (collectedFoods[food]) {
            item.classList.add("collected");
        }
        item.title = food;
        displayDiv.appendChild(item);

        const finalItem = item.cloneNode(true);
        finalDisplayDiv.appendChild(finalItem);
    });

    if (Object.keys(collectedFoods).length === foodNames.length) {
        showScreen("final-dish-display");
    }
};

const collectFood = (food) => {
    if (!collectedFoods[food]) {
        collectedFoods[food] = true;
        updateCollectedFoodsDisplay();
    }
};

document.addEventListener("DOMContentLoaded", () => {
    showScreen("main-menu"); // 直接顯示主選單

    document.getElementById("start-button")?.addEventListener("click", () => showScreen("main-menu"));
    document.getElementById("level1-button")?.addEventListener("click", () => showLevel('level1'));
    document.getElementById("level2-button")?.addEventListener("click", () => showLevel('level2'));
    document.getElementById("level3-button")?.addEventListener("click", () => showLevel('level3'));
    document.getElementById("level4-button")?.addEventListener("click", () => showLevel('level4'));
    document.getElementById("level5-button")?.addEventListener("click", () => showLevel('level5'));
    document.getElementById("return-to-start")?.addEventListener("click", () => {
        Object.keys(collectedFoods).forEach(key => delete collectedFoods[key]);
        updateCollectedFoodsDisplay();
        showScreen("start-screen");
    });
    
    updateCollectedFoodsDisplay();
});

const showLevel = (levelId) => {
    showScreen(levelId);
    switch (levelId) {
        case 'level1': initLevel1(); break;
        case 'level2': initLevel2(); break;
        case 'level3': initLevel3(); break;
        case 'level4': initLevel4(); break;
        case 'level5': initLevel5(); break;
    }
};

// Level 1: Memory Game
let flippedCards = [];
let matchedPairs = 0;
const memoryBoard = document.getElementById("memory-game-board");
const level1Message = document.getElementById("level1-message");
const restartLevel1Btn = document.getElementById("restart-level1");
const nextLevel1Btn = document.getElementById("next-level1");

const initLevel1 = () => {
    flippedCards = [];
    matchedPairs = 0;
    level1Message.classList.add("hidden");
    restartLevel1Btn.classList.add("hidden");
    nextLevel1Btn.classList.add("hidden");
    memoryBoard.innerHTML = '';
    const cards = [
        { id: 1, img: "https://imgur.com/card_fengyan_a.png" }, { id: 1, img: "https://imgur.com/card_fengyan_b.png" },
        { id: 2, img: "https://imgur.com/card_rouyuan_a.png" }, { id: 2, img: "https://imgur.com/card_rouyuan_b.png" },
        { id: 3, img: "https://imgur.com/card_kuangrou_a.png" }, { id: 3, img: "https://imgur.com/card_kuangrou_b.png" },
        { id: 4, img: "https://imgur.com/card_guashan_a.png" }, { id: 4, img: "https://imgur.com/card_guashan_b.png" }
    ].sort(() => Math.random() - 0.5);

    cards.forEach(card => {
        const cardElement = document.createElement("div");
        cardElement.classList.add("memory-card");
        cardElement.dataset.id = card.id;
        cardElement.innerHTML = `
            <div class="card-face card-back"></div>
            <div class="card-face card-front"><img src="${card.img}" alt="鳳眼糕"></div>
        `;
        cardElement.addEventListener("click", () => flipCard(cardElement));
        memoryBoard.appendChild(cardElement);
    });
};

const flipCard = (card) => {
    if (flippedCards.length < 2 && !card.classList.contains("flipped") && !card.classList.contains("matched")) {
        card.classList.add("flipped");
        flippedCards.push(card);

        if (flippedCards.length === 2) {
            setTimeout(checkForMatch, 1000);
        }
    }
};

const checkForMatch = () => {
    const [card1, card2] = flippedCards;
    if (card1.dataset.id === card2.dataset.id) {
        card1.classList.add("matched");
        card2.classList.add("matched");
        matchedPairs++;
        if (matchedPairs === 4) {
            level1Message.textContent = "恭喜！您找到了所有鳳眼糕！";
            level1Message.classList.remove("hidden");
            collectFood("鳳眼糕");
            nextLevel1Btn.classList.remove("hidden");
        }
    } else {
        card1.classList.remove("flipped");
        card2.classList.remove("flipped");
    }
    flippedCards = [];
};

restartLevel1Btn?.addEventListener("click", initLevel1);
nextLevel1Btn?.addEventListener("click", () => showScreen("main-menu"));


// Level 2: Quiz Game
const questionText = document.getElementById("question-text");
const answersContainer = document.getElementById("answers-container");
const level2Message = document.getElementById("level2-message");
const restartLevel2Btn = document.getElementById("restart-level2");
const nextLevel2Btn = document.getElementById("next-level2");

let currentQuestionIndex = 0;
const quizQuestions = [
    { question: "彰化肉圓的內餡通常不包含以下哪種食材？", answers: ["豬肉", "香菇", "筍子", "蝦仁"], correct: "蝦仁" },
    { question: "彰化肉圓最常見的烹調方式是？", answers: ["清蒸", "油炸", "水煮", "烘烤"], correct: "油炸" },
    { question: "肉圓通常會淋上什麼醬汁？", answers: ["花生醬", "甜辣醬", "番茄醬", "芥末醬"], correct: "甜辣醬" }
];

const initLevel2 = () => {
    currentQuestionIndex = 0;
    level2Message.classList.add("hidden");
    restartLevel2Btn.classList.add("hidden");
    nextLevel2Btn.classList.add("hidden");
    loadQuestion();
};

const loadQuestion = () => {
    if (currentQuestionIndex < quizQuestions.length) {
        const q = quizQuestions[currentQuestionIndex];
        questionText.textContent = q.question;
        answersContainer.innerHTML = '';
        q.answers.forEach(answer => {
            const button = document.createElement("button");
            button.classList.add("answer-button");
            button.textContent = answer;
            button.addEventListener("click", () => selectAnswer(button, answer, q.correct));
            answersContainer.appendChild(button);
        });
    } else {
        level2Message.textContent = "恭喜！您成功通過肉圓挑戰！";
        level2Message.classList.remove("hidden");
        collectFood("肉圓");
        nextLevel2Btn.classList.remove("hidden");
    }
};

const selectAnswer = (button, selectedAnswer, correctAnswer) => {
    if (selectedAnswer === correctAnswer) {
        button.classList.add("correct");
        setTimeout(() => {
            currentQuestionIndex++;
            loadQuestion();
        }, 500);
    } else {
        button.classList.add("incorrect");
        level2Message.textContent = "答案錯誤，請重新挑戰！";
        level2Message.classList.remove("hidden");
        restartLevel2Btn.classList.remove("hidden");
        answersContainer.querySelectorAll(".answer-button").forEach(btn => btn.disabled = true);
    }
};

restartLevel2Btn?.addEventListener("click", initLevel2);
nextLevel2Btn?.addEventListener("click", () => showScreen("main-menu"));


// Level 3: Collect Game
const collectGameArea = document.getElementById("collect-game-area");
const currentScoreSpan = document.getElementById("current-score");
const targetScoreSpan = document.getElementById("target-score");
const level3Message = document.getElementById("level3-message");
const restartLevel3Btn = document.getElementById("restart-level3");
const nextLevel3Btn = document.getElementById("next-level3");

let score = 0;
const targetScore = 10;
let itemInterval;
let gameDuration = 30000; // 30 seconds
let gameTimer;

const initLevel3 = () => {
    score = 0;
    currentScoreSpan.textContent = score;
    targetScoreSpan.textContent = targetScore;
    collectGameArea.innerHTML = '';
    level3Message.classList.add("hidden");
    restartLevel3Btn.classList.add("hidden");
    nextLevel3Btn.classList.add("hidden");

    clearInterval(itemInterval);
    clearTimeout(gameTimer);

    itemInterval = setInterval(createFallingItem, 1000);
    gameTimer = setTimeout(endLevel3, gameDuration);
};

const createFallingItem = () => {
    const item = document.createElement("div");
    item.classList.add("falling-item");
    item.style.left = Math.random() * (collectGameArea.clientWidth - 50) + "px";
    item.style.backgroundImage = `url('https://imgur.com/pork_belly.png')`; // 假設這是爌肉圖片
    item.style.top = "-50px";
    item.style.animationDuration = (Math.random() * 2 + 3) + "s";
    collectGameArea.appendChild(item);

    item.addEventListener("click", () => {
        score++;
        currentScoreSpan.textContent = score;
        item.remove();
    });

    item.addEventListener("animationend", () => {
        if (item.parentNode === collectGameArea) {
            item.remove();
        }
    });
};

const endLevel3 = () => {
    clearInterval(itemInterval);
    collectGameArea.innerHTML = '';
    if (score >= targetScore) {
        level3Message.textContent = `恭喜！您收集了 ${score} 個食材，成功製作爌肉飯！`;
        collectFood("爌肉飯");
        nextLevel3Btn.classList.remove("hidden");
    } else {
        level3Message.textContent = `很可惜，您只收集了 ${score} 個食材，請重新挑戰！`;
        restartLevel3Btn.classList.remove("hidden");
    }
    level3Message.classList.remove("hidden");
};

restartLevel3Btn?.addEventListener("click", initLevel3);
nextLevel3Btn?.addEventListener("click", () => showScreen("main-menu"));


// Level 4: Maze Game
const mazeCanvas = document.getElementById('maze-canvas');
const mazeCtx = mazeCanvas.getContext('2d');
const level4Message = document.getElementById("level4-message");
const restartLevel4Btn = document.getElementById("restart-level4");
const nextLevel4Btn = document.getElementById("next-level4");

const mazeSize = 15;
const cellSize = 30;
let maze = [];
let player = { x: 0, y: 0 };
let foods = [];

const initLevel4 = () => {
    mazeCanvas.width = mazeSize * cellSize;
    mazeCanvas.height = mazeSize * cellSize;
    level4Message.classList.add("hidden");
    restartLevel4Btn.classList.add("hidden");
    nextLevel4Btn.classList.add("hidden");
    
    generateMaze();
    player = { x: 0, y: 0 };
    placeFoods();
    drawMaze();
};

const generateMaze = () => {
    maze = Array.from({ length: mazeSize }, () => Array(mazeSize).fill(1)); // 1 for wall, 0 for path
    const visited = Array.from({ length: mazeSize }, () => Array(mazeSize).fill(false));
    const stack = [];

    const startX = Math.floor(Math.random() * mazeSize);
    const startY = Math.floor(Math.random() * mazeSize);
    stack.push({ x: startX, y: startY });
    visited[startY][startX] = true;
    maze[startY][startX] = 0;

    const dx = [0, 0, 1, -1];
    const dy = [1, -1, 0, 0];

    while (stack.length > 0) {
        const { x, y } = stack[stack.length - 1];
        const neighbors = [];

        for (let i = 0; i < 4; i++) {
            const nx = x + dx[i] * 2;
            const ny = y + dy[i] * 2;

            if (nx >= 0 && nx < mazeSize && ny >= 0 && ny < mazeSize && !visited[ny][nx]) {
                neighbors.push({ x: nx, y: ny, px: x + dx[i], py: y + dy[i] });
            }
        }

        if (neighbors.length > 0) {
            const next = neighbors[Math.floor(Math.random() * neighbors.length)];
            maze[next.py][next.px] = 0;
            maze[next.y][next.x] = 0;
            visited[next.y][next.x] = true;
            stack.push({ x: next.x, y: next.y });
        } else {
            stack.pop();
        }
    }
};

const placeFoods = () => {
    foods = [];
    let count = 0;
    while (count < 5) { // Place 5 foods
        const x = Math.floor(Math.random() * mazeSize);
        const y = Math.floor(Math.random() * mazeSize);
        if (maze[y][x] === 0 && (x !== player.x || y !== player.y) && !foods.some(f => f.x === x && f.y === y)) {
            foods.push({ x, y, collected: false });
            count++;
        }
    }
};

const drawMaze = () => {
    mazeCtx.clearRect(0, 0, mazeCanvas.width, mazeCanvas.height);

    for (let y = 0; y < mazeSize; y++) {
        for (let x = 0; x < mazeSize; x++) {
            if (maze[y][x] === 1) {
                mazeCtx.fillStyle = '#663300'; // Wall color
                mazeCtx.fillRect(x * cellSize, y * cellSize, cellSize, cellSize);
            }
        }
    }

    // Draw foods
    foods.forEach(food => {
        if (!food.collected) {
            const img = new Image();
            img.src = "https://imgur.com/guashan_item.png"; // 卦山燒圖片
            img.onload = () => {
                mazeCtx.drawImage(img, food.x * cellSize + 5, food.y * cellSize + 5, cellSize - 10, cellSize - 10);
            };
            if (img.complete) { // If image is already loaded (from cache)
                mazeCtx.drawImage(img, food.x * cellSize + 5, food.y * cellSize + 5, cellSize - 10, cellSize - 10);
            }
        }
    });

    // Draw player
    mazeCtx.fillStyle = '#FF4500'; // Player color
    mazeCtx.beginPath();
    mazeCtx.arc(player.x * cellSize + cellSize / 2, player.y * cellSize + cellSize / 2, cellSize / 3, 0, Math.PI * 2);
    mazeCtx.fill();
};

const movePlayer = (dx, dy) => {
    const newX = player.x + dx;
    const newY = player.y + dy;

    if (newX >= 0 && newX < mazeSize && newY >= 0 && newY < mazeSize && maze[newY][newX] === 0) {
        player.x = newX;
        player.y = newY;
        checkFoodCollection();
        drawMaze();
        checkWinCondition();
    }
};

const checkFoodCollection = () => {
    foods.forEach(food => {
        if (!food.collected && food.x === player.x && food.y === player.y) {
            food.collected = true;
            drawMaze(); // Redraw to remove collected food
        }
    });
};

const checkWinCondition = () => {
    if (foods.every(f => f.collected)) {
        level4Message.textContent = "恭喜！您收集了所有卦山燒，成功走出迷宮！";
        level4Message.classList.remove("hidden");
        collectFood("卦山燒");
        nextLevel4Btn.classList.remove("hidden");
    }
};

document.addEventListener('keydown', (e) => {
    if (document.getElementById('level4').classList.contains('hidden')) return;
    switch (e.key) {
        case 'ArrowUp': movePlayer(0, -1); break;
        case 'ArrowDown': movePlayer(0, 1); break;
        case 'ArrowLeft': movePlayer(-1, 0); break;
        case 'ArrowRight': movePlayer(1, 0); break;
    }
});

restartLevel4Btn?.addEventListener("click", initLevel4);
nextLevel4Btn?.addEventListener("click", () => showScreen("main-menu"));


// Level 5: Oyster Omelette Game
const oysterGameArea = document.getElementById("oyster-game-area");
const oysterCurrentScoreSpan = document.getElementById("oyster-current-score");
const oysterTimeSpan = document.getElementById("oyster-time");
const level5Message = document.getElementById("level5-message");
const restartLevel5Btn = document.getElementById("restart-level5");
const nextLevel5Btn = document.getElementById("next-level5");

let oysterScore = 0;
let oysterTime = 30;
let oysterTimerInterval;
let oysterItemInterval;

const initLevel5 = () => {
    oysterScore = 0;
    oysterTime = 30;
    oysterCurrentScoreSpan.textContent = oysterScore;
    oysterTimeSpan.textContent = oysterTime;
    oysterGameArea.innerHTML = '';
    level5Message.classList.add("hidden");
    restartLevel5Btn.classList.add("hidden");
    nextLevel5Btn.classList.add("hidden");

    clearInterval(oysterTimerInterval);
    clearInterval(oysterItemInterval);

    oysterTimerInterval = setInterval(updateOysterTime, 1000);
    oysterItemInterval = setInterval(createOysterItem, 1000);
};

const createOysterItem = () => {
    const item = document.createElement("div");
    item.classList.add("oyster-item");
    item.style.left = Math.random() * (oysterGameArea.clientWidth - 80) + "px";
    item.style.top = Math.random() * (oysterGameArea.clientHeight - 80) + "px";

    const isCorrect = Math.random() < 0.7; // 70% chance of being correct
    item.dataset.correct = isCorrect;
    item.style.backgroundImage = `url(${isCorrect ? 'https://imgur.com/correct_oyster.png' : 'https://imgur.com/wrong_oyster.png'})`; // 替換為蚵仔煎圖片和錯誤食物圖片

    item.addEventListener("click", () => {
        if (item.dataset.correct === "true") {
            oysterScore++;
            oysterCurrentScoreSpan.textContent = oysterScore;
            item.classList.add("correct");
        } else {
            oysterScore = Math.max(0, oysterScore - 1); // Lose 1 point for wrong click
            oysterCurrentScoreSpan.textContent = oysterScore;
            item.classList.add("wrong");
        }
        item.style.pointerEvents = 'none'; // Disable further clicks
        setTimeout(() => item.remove(), 300); // Remove after a short delay
    });

    oysterGameArea.appendChild(item);

    // Remove item after a certain time if not clicked
    setTimeout(() => {
        if (item.parentNode === oysterGameArea) {
            item.remove();
        }
    }, 2000); // Items disappear after 2 seconds
};

const updateOysterTime = () => {
    oysterTime--;
    oysterTimeSpan.textContent = oysterTime;
    if (oysterTime <= 0) {
        clearInterval(oysterTimerInterval);
        clearInterval(oysterItemInterval);
        endLevel5();
    }
};

const endLevel5 = () => {
    oysterGameArea.innerHTML = '';
    if (oysterScore >= 15) { // Target score for winning
        level5Message.textContent = `恭喜！您在時間內完成了蚵仔煎挑戰，得分：${oysterScore}！`;
        collectFood("蚵仔煎");
        nextLevel5Btn.classList.remove("hidden");
    } else {
        level5Message.textContent = `時間到！您的得分是：${oysterScore}。請重新挑戰！`;
        restartLevel5Btn.classList.remove("hidden");
    }
    level5Message.classList.remove("hidden");
};

restartLevel5Btn?.addEventListener("click", initLevel5);
nextLevel5Btn?.addEventListener("click", () => showScreen("main-menu"));
```

### Your CSS

```css
body { margin: 0; font-family: 'Arial', sans-serif; background-color: #f0f0f0; display: flex; justify-content: center; align-items: center; min-height: 100vh; overflow: hidden; }
.game-container { width: 90%; max-width: 800px; background-color: #fff; border-radius: 15px; box-shadow: 0 0 20px rgba(0,0,0,0.2); text-align: center; overflow: hidden; position: relative; min-height: 600px; display: flex; flex-direction: column; justify-content: center; align-items: center; }
.game-section, .level-section { width: 100%; height: 100%; position: absolute; top: 0; left: 0; display: flex; flex-direction: column; justify-content: center; align-items: center; padding: 20px; box-sizing: border-box; }
.hidden { display: none !important; }
h1, h2, h3 { color: #333; margin-bottom: 20px; }
p { color: #666; margin-bottom: 15px; }
.intro-text { font-size: 1.1em; line-height: 1.6; }
.shine-button { background-color: #ff6347; color: white; padding: 12px 25px; border: none; border-radius: 30px; font-size: 1.1em; cursor: pointer; transition: all 0.3s ease; box-shadow: 0 4px 10px rgba(0,0,0,0.2); position: relative; overflow: hidden; z-index: 1; }
.shine-button:hover { transform: translateY(-3px); box-shadow: 0 6px 15px rgba(0,0,0,0.3); }
.shine-button::after { content: ''; position: absolute; top: 50%; left: -100%; width: 30px; height: 100%; background: rgba(255,255,255,0.4); transform: skewX(-20deg); transition: all 0.8s ease; }
.shine-button:hover::after { left: 100%; }
.screen-background, .level-background { background-size: cover; background-position: center; }
.screen-background::before, .level-background::before { content: ''; position: absolute; top: 0; left: 0; width: 100%; height: 100%; background-color: rgba(255, 255, 255, 0.6); z-index: 0; }
.screen-background > *, .level-background > * { z-index: 1; position: relative; }
#start-screen { background-image: url('https://imgur.com/your_start_background_image.jpg'); } /* 請替換為您的圖片網址 */
#main-menu { background-image: url('https://imgur.com/your_main_menu_background_image.jpg'); } /* 請替換為您的圖片網址 */
.level-select-button { margin: 10px; min-width: 200px; }
#foods-display { display: flex; flex-wrap: wrap; justify-content: center; margin-bottom: 20px; }
.collected-food-item { width: 80px; height: 80px; background-size: cover; background-position: center; margin: 5px; border-radius: 10px; border: 2px solid transparent; transition: border 0.3s ease; }
.collected-food-item.collected { border-color: #4CAF50; box-shadow: 0 0 8px rgba(76, 175, 80, 0.6); }

/* Level 1: Memory Game */
#level1 { background-image: url('https://imgur.com/your_level1_background_image.jpg'); } /* 請替換為您的圖片網址 */
.memory-board { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; width: 400px; height: 400px; perspective: 1000px; }
.memory-card { width: 100%; height: 100%; background-color: #f8f8f8; border-radius: 8px; cursor: pointer; transform-style: preserve-3d; transition: transform 0.5s; position: relative; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
.memory-card.flipped { transform: rotateY(180deg); }
.memory-card .card-face { position: absolute; width: 100%; height: 100%; backface-visibility: hidden; display: flex; justify-content: center; align-items: center; font-size: 2em; border-radius: 8px; }
.memory-card .card-front { background-color: #FFDAB9; transform: rotateY(180deg); }
.memory-card .card-back { background-color: #8B4513; }
.memory-card img { max-width: 80%; max-height: 80%; }
.memory-card.matched { opacity: 0.5; cursor: default; }

/* Level 2: Quiz Game */
#level2 { background-image: url('https://imgur.com/your_level2_background_image.jpg'); } /* 請替換為您的圖片網址 */
#question-box { background-color: rgba(255,255,255,0.9); padding: 25px; border-radius: 10px; margin-bottom: 20px; max-width: 600px; width: 100%; box-shadow: 0 0 15px rgba(0,0,0,0.1); }
#question-text { font-size: 1.4em; color: #333; margin-bottom: 20px; }
#answers-container { display: flex; flex-direction: column; }
.answer-button { background-color: #ADD8E6; color: #333; padding: 12px 20px; margin: 8px 0; border: none; border-radius: 8px; font-size: 1.1em; cursor: pointer; transition: background-color 0.3s ease, transform 0.2s ease; }
.answer-button:hover { background-color: #87CEEB; transform: translateX(5px); }
.answer-button.correct { background-color: #90EE90; }
.answer-button.incorrect { background-color: #FFB6C1; }

/* Level 3: Collect Game */
#level3 { background-image: url('https://imgur.com/your_level3_background_image.jpg'); } /* 請替換為您的圖片網址 */
#collect-game-area { width: 100%; height: 400px; background-color: rgba(0,0,0,0.1); border-radius: 10px; position: relative; overflow: hidden; margin-bottom: 20px; }
.falling-item { width: 50px; height: 50px; position: absolute; background-size: contain; background-repeat: no-repeat; cursor: pointer; animation: fall linear forwards; }
#score-display { font-size: 1.5em; color: #333; }
#current-score, #target-score { font-weight: bold; }

/* Level 4: Maze Game */
#level4 { background-image: url('https://imgur.com/your_level4_background_image.jpg'); } /* 請替換為您的圖片網址 */
#maze-container { background-color: #fff; border-radius: 10px; overflow: hidden; max-width: 500px; max-height: 500px; width: 90%; height: 90vw; display: flex; justify-content: center; align-items: center; }
#maze-canvas { display: block; background-color: #f0f0f0; border-radius: 8px; }

/* Level 5: Oyster Game */
#level5 { background-image: url('https://imgur.com/your_level5_background_image.jpg'); } /* 請替換為您的圖片網址 */
#oyster-game-area { width: 100%; height: 400px; background-color: rgba(0,0,0,0.1); border-radius: 10px; position: relative; margin-bottom: 20px; }
.oyster-item { width: 80px; height: 80px; background-size: cover; background-position: center; border-radius: 50%; position: absolute; cursor: pointer; border: 2px solid transparent; }
.oyster-item.correct { border-color: #4CAF50; }
.oyster-item.wrong { border-color: #F44336; }
#oyster-score-time { font-size: 1.5em; color: #333; }
#oyster-current-score, #oyster-time { font-weight: bold; }

/* Final Dish Display */
#final-dish-display { background-image: url('https://imgur.com/your_final_background_image.jpg'); } /* 請替換為您的圖片網址 */
#collected-foods-final { display: flex; flex-wrap: wrap; justify-content: center; margin-top: 20px; }
#return-to-start { margin-top: 20px; }

.message-box { background-color: rgba(255, 255, 255, 0.95); padding: 15px 25px; border-radius: 10px; margin-top: 20px; font-size: 1.2em; color: #333; box-shadow: 0 4px 8px rgba(0,0,0,0.1); }
```
